### ISSUE TITLE
Feedback from first project showcase on 18 Sept 2018

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#110]
- [ ] Add a snapshot of the version of the algorithm / pop charact. / site charact. for each ANC contact in case the algorithm or the pop or site characteristics change over time.
- [ ] Idea: Show the filter numbers as the user is selecting filters (Note: although this is a nice-to-have, we agreed this is not something we will be doing)
- [x] Date constraint for date of death in ANC close form - I looked this up and the constraint should be <={today}. We can add an earlier date constraint, but that requires critical thinking and consensus from the team on what appropriate earlier date constraints would be for all date variables in the form, which is something we didn't have time for, given the length and complexity of the all of the other content in the data dictionary.
- [ ] Think this one is already covered, but when a user revisits a contact container, they should be directed to the first empty required field in that contact container.
- [x] Buttons on save contact widget don't look like buttons - already left a comment on the issue (https://github.com/OpenSRP/opensrp-client-anc/issues/43).
- [x] The section labels for the previous and next buttons on the individual section pages within the contact containers can be de-prioritized.

**Comment by rowo** [comment]
A few more comments from playing around with app recently:
- [ ] You should be able to skip around contact subsections without completing questions. Right now I am getting blocked when I hit the top right arrow and I think it's because some text-input required fields are empty.
- [ ] There are some form things but probably just not done — like the refer button remains if I check and uncheck a danger sign, pill buttons for number birthds, etc. should be taller..
- [ ] When exiting a contact section, it shouldn't need confirmation and should just save
- [ ] QR code scanner should open up vertically, right now it goes to horizontal mode
- [ ] Is there a way to make all of the contact buttons and the ANC history responsively resize to always appear on a single screen? This consistency is important to build muscle memory.
- [ ] This may not be indicated in any requirements, but can we show a fixed contact button on client profiles if something is either due or overdue?

**Comment by cagulas** [comment]
Moved all remaining comments into new issues, closing this one.
