### ISSUE TITLE
Feedback from ANC showcase on 13 Nov 2018

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#150]
- [ ] The "NEXT" and "PREVIOUS" buttons are really small on contact pages

- [ ] For discussion: We may need to consider differentiating between discarding most recent changes vs. discarding the entire contact (but downside of the latter is if they accidentally hit this when they meant to hit the former, they lose all of their previous work). The context for this is that a user might work on the contact on multiple occasions, so discarding their most recent changes vs. discarding the entire contact are two very different things. May not be needed for now, but something to keep in mind. Interestingly, I think the original intention for these buttons was for the discard to always discard the entire contact, but the team actually implemented it in a different way that might work better, that is the discard is a discard of only the most recent changes. This makes sense, actually, but we may need to edit the text on the buttons to match. Right now, the save button says hit save to continue contact at a later time, but if you discard your most recent changes, you can still continue the contact at a later time. So perhaps we can change the Save button to save "Save - all changes will be saved" and the discard to say "Discard - all changes will be lost" @rowo what do you think?

- [ ] The logic for 40/41 weeks is wrong. The GA refers to how many **completed** weeks of pregnancy, i.e. if she is 40 weeks, then that means she has completed 40 weeks of pregnancy. So at GA of 40 weeks, she is due for her last contact. At GA 41 weeks, she is due to delivery, if she hasn't already. @ndegwamartin Does this make sense?

**Comment by rowo** [comment]
Feedback from Tigest, email on Nov 19:

- I thought it was not as intuitive that you had to scroll down to see the toaster message related to constipation.  For example, in the screen shot ending in 06502, I could see the message related to leg cramps, but didn’t realize there was also another message related to fiber until you scroll down (screen shot 065006).  I guess since when they go to the next screen, they will see it, but it made it feel like a less seamless process. One thought was to maybe have the message that relates to the checked box come immediately after it.  Or maybe something can indicate that they should scroll down for all the counselling messages.  
- Matt and I were discussing whether the NEXT or SUBMIT buttons should generally be more pronounced than PREVIOUS, either by making it bold or putting in a blue shaded rectangle.
Is it possible to generally add scrolling function on the side-not sure if this will mess up the clean design. I find scrollbars useful for myself to see how much I will need to be going through to get to the bottom of a page and highlighting that there is more to cover.  For example, in screenshot 065117, I know that I probably have to scroll but it may not be immediately obvious to some health workers who may not interact with smartphones as much.

**Comment by cagulas** [comment]
Closing this and moved all still-relevant issues to new ones.
