### ISSUE TITLE
Implement ANC Register Form

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-anc#2]
This form will be used to register a new patient in the application.

- [x] Design and set up client database schema
- [x] User interface
- [x] Form validation
- [x] Form persistence
- [x] Unit Tests
~- [ ]  Implement locations (location tree)~ Register form uses input text

**Comment by ndegwamartin** [comment]
- [ ] Design and set up client database schema
- [ ] User interface
- [ ] Form validation and persistence

**Comment by cagulas** [comment]
@ndegwamartin Please note the new question about reminders for care on row 18 in the data dict.

**Comment by cagulas** [comment]
QA 11th Oct build:

- [ ] Change name of form to "ANC Registration"
- [ ] Even though you can press the picture and qr code buttons, they look like they are not active. Can we change them to a dark blue background so they look active? @rowo Can you comment on this point. It looks like this is like this because fields become blue and active when you select them, greyed out otherwise, for the entire form. 
- [ ] The DOB field isn't shown. We need to show both the DOB unknown checkbox at the same time as the DOB field. One or the other is required, but both cannot be filled in.
- [ ] Change "Enter Age if DOB unknown" to just "Age" as per the data dictionary.

**Comment by cagulas** [comment]
QA 16th Oct build:

- [ ] Add space between "birth(DOB)"
- [ ] Age field is missing the constraint: Must be 15-49, inclusive.
- [ ] Mobile phone number missing constraint: Must be 10 digits.
- [ ] Alternate contact phone number also missing the above constraint.
- [ ] Can we update the text for "Reminders throughout pregnancy" to what it says in the data dictionary: "Does she want to receive reminders for care and messages regarding her health throughout her pregnancy?" If this can't be done due to space reasons, can we add an info icon with the text from the data dictionary?

**Comment by cagulas** [comment]
QA 18th Oct build:

- [ ] Add space between "birth(DOB)" - NOT FIXED

I am using the Samsung J5 to test. The last two issues didn't re-occur with this build.

**Comment by cagulas** [comment]
The two issues with the camera and qr code re-occurred with this latest build.

**Comment by cagulas** [comment]
Closing this issue. The remaining issue about the camera moved to new issue.
