### ISSUE TITLE
Further performance improvements

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#218]
We should take another look at the performance of the contact workflow. It's taking a long time to open a contact quick check page, and in general, there is a 1-2 second delay when moving to the next section, for popups to open, etc.

**Comment by cafootitt** [comment]
Performance improvements especially needed on:
- [ ] Current Pregnancy section in Profile
- [ ] Expansion panels in Tests & C&T containers in general are quite slow, as well as responding to questions within the expansion panels.

**Comment by cafootitt** [comment]
@ellykits Why is the blocked label added?

**Comment by ellykits** [comment]
@cafootitt The performance improvement is blocked since it is solely dependent on the optimization of the form library used in the app (Native form). Discussion and work on optimizing native form is ongoing as its part of the roadmap for this quarter.

**Comment by cafootitt** [comment]
Ok, thanks @ellykits.

What about the expansion panel? Is this tied into native form performance as well, or can the expansion panel performance be improved independently?

**Comment by ellykits** [comment]
The expansion panel uses a functionality of native form called subforms (a form embedded into the main form) and it gets slow because of the calculations performed by the Rules Engine which is also part of the native form. Thus improving the performance of the library would impact that of the expansion panel.
