### ISSUE TITLE
All counseling & treatment tasks in C&T container do not need RECORD option

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#256]
The RECORD another result is only required for Tests, not Counseling & Treatment, so we need to remove the RECORD button that appears for all counseling & treatment tasks. 

~~Similarly, I'm thinking we don't need to have the UNDO button either. This is because if they need to make changes, they can tap back into the widget and change their responses.~~ **CG: Ok to leave Undo as is**

Finally, in looking at the screen (see below), I think we can streamline this a bit more. It's a bit overkill to show the heading and then show the full question and then show done. If the counseling is done, I think we can just show the heading with the green check mark and not even show any data inputs underneath it. If it's not done, I think we can show the not done reason underneath only, for e.g. "Reason:     Other: Left early" for example. If the simplest thing to do is just not show any inputs below and just show the green check or grey not done icon, I'd be happy with that as well for now.

![Screenshot_20190402-111705](https://user-images.githubusercontent.com/3488986/55387131-8850bc00-5539-11e9-8415-2b7ab5d8f5d5.png)

**Comment by rowo** [comment]
1) Agree record isn't needed
2) Having the "Undo" could be clearer and more obvious to match what happens elsewhere than tapping back into it. I am okay with removing it, but I don't see an issue leaving it in either since it provides a reset back to a "not answered" state rather than forcing a done or not done answer — if that is ever an option.
3) Agree, we don't need the sub question data unless it's useful to reference or verify. It was meant as a place data could show up but not required. Sorry this wasn't clear in the designs, but that was the goal.

**Comment by ellykits** [comment]
@cagulas Some sub-questions have more than one question as shown in the screenshot below. Plus what if there are more than one counselling questions with different statuses as shown in the **Birth preparedness and complications and readiness** section. How would we know the status if **done** or **not done** if we only show the headers? Or are these scenarios not likely to happen?

![Screenshot_1554984423](https://user-images.githubusercontent.com/26865532/55955957-7c68a680-5c6b-11e9-9f29-bc8bde367631.png)

**Comment by cagulas** [comment]
Closing this for now, since the Record button is removed, but we need to have a separate discussion around the question of what inputs to show.
