### ISSUE TITLE
Prevent the jump back to pulse rate field when filling in abnormal exam results

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#297]
On PE container, when you fill in abnormal test results for any of the exam questions, when you close the widget, the page always jumps back up to the last text entry field on the page, which in my case is pulse rate. This is a pretty poor experience for the users, as one has to continue to scroll to their last question on the page.

**Comment by ellykits** [comment]
@cafootitt This has to do with the with the way Android system requests focus on input fields and how the views are rendered using native form. Android assigns focus to views that are on the same hierarchy. In our case since we are using a radio button within a nested layout (that has the radio button itself, specify text that launches a popup, view for showing extra info and sometimes info icon) the text input is thus not on the same level with the radio button that's why it falls back to the last edited input field.

What we can however look into is clearing the focus on the main page when a popup is launched. Will try that out in native form.

**Comment by dubdabasoduba** [comment]
@ellykits I have implemented you above suggested fix whenever the popup is opened. I am yet to test it with the fix that forces the first required item in the form to request focus.

**Comment by cafootitt** [comment]
1.2.2. - lgtm
