### ISSUE TITLE
Implement ANC Close Form

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-anc#3]
This form will be used to remove/archive a patient record

- [x] User interface
- [x] Form validation and persistence
- [x] Remove Patient functionality
- [x] Unit Tests

**Comment by cagulas** [comment]
QA 11th Oct build:

- [ ] Please revert the exit form confirmation message to what is was before. The "changes" message is for forms that were opened for editing, not new forms opened like this one. Also, there is no reason to put "changes" in quotations.

**Comment by cagulas** [comment]
QA 18th Oct build:

- [ ] This form is broken. Please check all the skip logic. When I open the form, instead of seeing the first question, I'm seeing the specific fields for the live birth option only.

![screenshot_20181018-103133](https://user-images.githubusercontent.com/3488986/47138071-1523f800-d2c1-11e8-8c24-462bece02a3f.png)

**Comment by cagulas** [comment]
QA:

- [ ] The date questions seem to be a lighter shade than the rest of the questions, but the indentation is fixed.
- [ ] Any delivery complications is a different font from the rest of the fields.
