### ISSUE TITLE
Profile container should have "Complete" status by default on subsequent contacts

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#309]
This wasn't specifically laid out in the original implementation issue, but it makes sense for this to be the expected behavior in the app. In the first contact visit, the user fills out the Profile container. These inputs are saved and shown in the second and all subsequent contacts. By default, since all required questions are responded to in the Profile container on subsequent contacts, the status should by default say Complete as soon as you open the contact page.

What happens right now is that on Contact 2, when you land on the contact container page after filling in Quick Check, the Profile status is null. If you open Profile container and then go back to contact container page, for some unknown reason, it shows 2 required fields. I go back to Profile container and go through each section and verify that all questions are answered. When I finish going through the sections and return to contact container page, Profile now says Complete even though I didn't change anything.

Expected behavior: When a user starts Contact 2 (or any contact after contact 1), the Profile container should show the "Complete" status. If this is difficult to do, then at least when they open Profile and return, it should show Complete instead of 2 required fields.

**Comment by ellykits** [comment]
@cafootitt  The reason profile form sometimes  shows that there are required fields when you have not gone through all the sections is because it also includes input fields that are are not visible in the count but once you visit the section the logic is able update the required fields count accordingly.

The question we had is: Will the user be required to open all the contact forms when a woman comes for visit. Another reason why the implementation is as is, is because when we update the logic to count required fields without opening the forms then it means we would need to show the required fields count for the other forms as well even when they have not been opened. We had this discussion and it was agreed to only show required fields count when a form has been opened.

**Comment by cafootitt** [comment]
>>The reason profile form sometimes shows that there are required fields when you have not gone through all the sections is because it also includes input fields that are are not visible in the count but once you visit the section the logic is able update the required fields count accordingly.

Ok for the above, this isn't really logical behavior. Or at least it's confusing. The Profile section is completely filled in, so there shouldn't be any input fields that are hidden that should be counted, because the inputs to Profile from the first contact make them hidden / not relevant. If they weren't counted in required field count in the first contact, why count them now? I can imagine this might be complex to handle, but we should talk through this more.

To answer your question, the user will be required to make sure all required fields are answered; otherwise, the Finalize button will not be active and they will not be able to finish the visit. However, the expected behavior is that the user shouldn't need to page through all sections of the Profile on subsequent visits just to trigger the relevance logic to update and the required field count to get triggered. The profile section on subsequent visits will be there for them to reference, but it shouldn't be required for them to go through each section of it to be able to finalize the contact.

**Comment by cafootitt** [comment]
Just to add to the above, we've gotten feedback from the client that this is confusing, because on subsequent contacts, the client is saying they weren't sure whether to edit the behavior questions in Profile or to enter them in S&F. The answer is they should enter them in S&F and not revise Profile questions.

To this end, having that "Complete" status already on the Profile container would help with this.

@rowo Can I also loop you into this for your input? Would showing "Complete" be sufficient, or, level of technical complexity aside for a moment, what would be the ideal user experience here?

**Comment by rowo** [comment]
I guess to answer Elly's prompt questions (which btw sounds like something that should be brought up at the project team level for a decision):
- Will the user be required to open all the contact forms when a woman comes for visit. **No, this was ever mentioned as a requirement**
- When we update the logic to count required fields without opening the forms then it means we would need to show the required fields count for the other forms as well even when they have not been opened. **What was the reasoning not to show required fields before opening the form? This seems valuable since it tells the user how much work they can expect to do. This isn't the same interaction as a required field warning pop up — it's more of a per-section progress indicator.**

It's only logical from a narrow sense if the user knows whats going on and if it's based on these initial assumptions which are incorrect. So I would say we should change this if there's bandwidth.

**Comment by cafootitt** [comment]
@rowo Cool, I'll try to find the issue tomorrow where we had the discussion, but in summary, we had a problem whereby the number of required fields shown when you open a contact would be the total number of required fields in the section, including all hidden fields that the user probably won't need to answer most of the time. For profile, I remember it being something like 40 required fields shown by default when you open the contact, and for C&T, something like over 140. We felt this would be more than a little overwhelming for a health worker, so we discussed that the containers would be blank upon opening, indicating that the health worker hasn't started that section yet. Only after opening the section, would the health worker see how many required fields they missed (if any) or the complete status when they were finished.

So the issue here is on the 2nd contact, the health worker doesn't need to fill out anything in Profile, it's there for them to refer to only; however, if they do open it and leave it again, it shows 2 required fields there, when in fact there are actually no fields for them to fill out. They have to page through ever screen in Profile for the required fields count to get updated to show the Complete status. So I'm wondering if we can just show the "Complete" status by default for Profile when you start the 2nd contact.

**Comment by rowo** [comment]
Ok, now I see the complication and how this "2nd contact" problem is more of an offshoot of an originating issue that hidden fields are calculated into the required total. Where it was easy to solve for the first contact by hiding the value, it's actually a new problem now.

@ellykits  So to understand the technical side — if the user goes to the Profile sections during Contact 1, all of the required hidden fields don't get counted as required anymore? And this is because each "page" of the Profile section does a calculation of if anything got "activated" as required and stores that, then uses the aggregate number for the required fields? For example, prior to opening Profile, an "Other" required text box would be included, but after opening, if the "Other" wasn't chosen, it would no longer be counted as required? Also, is this done by going through each page or is it enough just to open one page of the section?

@cafootitt This sounds like it goes beyond just changing what shows up (using a fixed "Complete" label), but also redoing how required fields are calculated. Wouldn't the problem be that there are actually 2 hidden required fields so if you tried submit, it would fail?

**Comment by cafootitt** [comment]
@rowo If I might step in for Elly since I'm awake early, all of your assumptions are correct:

>> So to understand the technical side — if the user goes to the Profile sections during Contact 1, all of the required hidden fields don't get counted as required anymore? **CORRECT** And this is because each "page" of the Profile section does a calculation of if anything got "activated" as required and stores that, then uses the aggregate number for the required fields? For example, prior to opening Profile, an "Other" required text box would be included, but after opening, if the "Other" wasn't chosen, it would no longer be counted as required? **CORRECT** Also, is this done by going through each page or is it enough just to open one page of the section? **Based on my testing, it seems it's done by going through each page**

To answer your questions to me, yes, the 2 hidden required fields would prevent the user from submitting the contact. Earlier, when I discussed with our team changing the way the required field count is done, it sounded quite complicated to do, hence the much simpler option of not showing the required count until the section was opened.

**Comment by ellykits** [comment]
@rowo your assumption of how the required fields are counted is CORRECT. But after consultation with @ndegwamartin, I guess it is right to say that as from contact 2 onward all the fields in Profile are complete since the user would be unable to save the contact without filling all the required fields (in the first contact) so it would be okay to indicate that profile is COMPLETE. Meaning as from the second contact  PROFILE container should have data entered on the previous contact unless changed.

**Comment by ellykits** [comment]
We can update the implementation to indicate PROFILE as complete from second contact. And adapt the functionality to always include data obtained from contact one for profile. (Which can always be updated when the user opens the form)

**Comment by rowo** [comment]
@ellykits So Carolyn's original issue, `What happens right now is that on Contact 2.... if you open Profile container and then go back to contact container page, for some unknown reason, it shows 2 required fields.` will be taken care of via the functionality adaptation to include data from contact 1? Since if you don't, just showing Complete would be incorrect and not let you submit?

**Comment by ellykits** [comment]
@rowo Exactly, I guess the issue will be addressed, when we can have the data for profile from the previous contact pre-loaded in contacts after the first one. And this would apply to any field that is only filled in contact one and is required by other forms for purposes of calculation._(It makes sense to populate them without having to first open the form. However if they are edited the data will of course be updated)_ The other issue on why invisible required fields are counted unless you navigate to the section where it is located, is due to the manner which the form library is designed.

I will discuss with the team on how to address that and at least have a workaround. @cafootitt what do you think. So the implementation will remain as is right now but will address @cafootitt's concern. Unless @rowo you have any suggestions.

**Comment by rowo** [comment]
@ellykits Thanks, I think this is will work out well. Can you let me know whether this workaround will either or both:
1. Preload information which will make invisible required fields not apply anymore
2. Remove the field requirement on the contacts 2–8 Profile sections only.

The reason I ask is I assume the first would not exactly be a workaround so for future apps/scenarios we would know preloading will be fine, whereas the second is kind of a custom fix you have to apply in these scenarios.

**Comment by cafootitt** [comment]
Forgot to close this from before. This is done.
