### ISSUE TITLE
Fix the edd calculation when GA is zero.  

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-anc#391]
In cases when the GA is `0` the EDD is also `0` fix this to make sure the EDD is a correct date which can be used for any date calculations.

**Comment by dubdabasoduba** [comment]
@ekigamba

**Comment by cafootitt** [comment]
This isn't a priority to fix, because it's not plausible scenario for a woman to be registered at 0 weeks pregnancy, so this event would never happen in real life.

**Comment by ekigamba** [comment]
@cafootitt Is this scenario possible in the current ANC app? 
We had some scenarios during GIZ Malawi UAT in which the GA was not available causing a lot of bugs.
Could we say that this was due to old data? If not and this is possible in the current ANC version, not having this or it being zero is a show stopper for some contacts & dates read wrongly in the ANC register.

**Comment by cafootitt** [comment]
@ekigamba I guess we shouldn't have any UAT scenarios where the GA is 0 weeks, because this would never happen in real life. I would recommend that those are removed as test cases.

**Comment by ekigamba** [comment]
@cafootitt Cool, we will retest this on our side with clean data & the most recent APK.

😆 I also understood what you meant that it would never happen in real life.

Do you think we need to enforce this on the profile page since this is bad input per. se?

Inputting the **GA From SFT or palpation -weeks** provides  validation and the weeks have to be  >= 4 weeks, however, when entered via the **LMP Known?** question, one can enter the current date and the **GA is taken 0 weeks, 0 days**

**Comment by cafootitt** [comment]
@ekigamba  Cool.
So I just checked the data dictionary again, and all the fields have constraints on them. As you say, ultrasound and SFH don't allow inputs below 4 weeks.

On the LMP field, the current constraint is:
`<= {today} and can't be an LMP that makes the woman more than 40 weeks GA (i.e. <= 40 weeks GA)`

I can talk to WHO and see if they agree we can adjust the constraint so that LMP must be at least 4 weeks ago.

**Comment by ekigamba** [comment]
@cafootitt Thanks 🙏 I think that would go a long way preventing wrong data input
