### ISSUE TITLE
Create mockup to show new contact button statuses

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#399]
WHO/Brazil user report feedback was that the user is confused about what next steps are after registration and general confusion over what the buttons mean on the register page. They are insistent that we make changes to make this more clear to the user. 

Below is my suggestion, because at the root of all of this feedback is that these buttons are unclear. If the user doesn't understand the color codes, it is confusing what the next step would be.

Other suggestions from WHO/Brazil was to add an intermediary step following registration to ask if the user wants to proceed immediately to the first contact. Either that or immediately launch contact 1 after registration.

![Screenshot_20191115-102222_WHO_ANC](https://user-images.githubusercontent.com/3488986/68924816-a69abd80-0792-11ea-97b8-d78143f78af1.jpg)

**Comment by rowo** [comment]
### Button labels
I think the buttons are unrelated to the behavior after registration since if you skip going back to the list after registration (their recommendation) you wouldn't see the buttons at all. So I wouldn't say they are the root of the issue, but maybe it's a potential solution to the new contact confusion with the most minimal work. It is also an improvement we could do without it being the only solution to the behavior after new contact.

Do you have a link to the feedback concerning confusion over the button states?

### New contact next step confusion

I think landing on the profile of the new contact is the expectation. That's how the Contacts app for my Android tablet and phone and iPhone and Mac computer work. 

Is this how the ANC app works now? I remember some cases where it goes back to the register list after registration and even if the new person shows at the top, it could be confusing.

So assuming you land on the profile after registration and there is a button to do the first contact — maybe on the profile there could be an overlay notification dialog that says something like "To start your first contact, tap the Contact 1 button on [name]'s profile" with an OK. And then the user sees the profile with the contact 1 button. This would train users a bit more on how to do the activity in the future rather than doing a special dialog that just prompts the first contact.

**Comment by cafootitt** [comment]
Feedback over confusion with the button states is on the last page of the [report](https://docs.google.com/document/d/1FqEfbpxFeDQ2BiFY1-ZUQ0gMvbFFIiGfgFiGTz0Cazg/edit#). See where it says "orange and blue buttons not intuitive".

No, the ANC app lands on the register list page after registration, not the profile page. I think this is because the profile page is still blank after registration and the Contact 1 button in profile page isn't displayed.

**Comment by rowo** [comment]
Is the profile page being blank after registration a bug or something that's impossible to do?

**Comment by cafootitt** [comment]
@rowo It's not a bug. It's not populated, because no contact visit has occurred yet to show any info:

![Screenshot_20191118-164550_WHO ANC](https://user-images.githubusercontent.com/3488986/69057500-0e673780-0a23-11ea-8a2a-7f57fcc4ba9c.jpg)

**Comment by rowo** [comment]
I created a new issue to address the post-registration confusion: https://github.com/OpenSRP/opensrp-client-anc/issues/401

For updates to the register list buttons in reaction to the feedback on "orange and blue buttons not intuitive", here is what the suggested updated styling and labels look like:

<img src="https://user-images.githubusercontent.com/1584163/69098305-4e7be980-0a26-11ea-9751-fd275d2febd4.png" width="300">
