### ISSUE TITLE
Implement Quick Check page in contact workflow

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#40]
The Quick Check page is the first screen the user sees when they begin a new contact. They will usually continue to a normal contact after filling in quick check, but if a danger sign is selected, the user will have the option of bypassing the contact and going straight to the summary submission page.

- [x] The Quick Check page, below, appears when the user taps on a Contact button (blue, red, or white, ie. due, overdue, or not currently do) in the main register page or selects the "Start contact" option in any woman's profile top right menu. Note: The user cannot start a new contact from the main register page if a contact is currently in progress (orange button) or is on due delivery (blue due delivery button) or just completed a contact (green check).

<img width="379" alt="screen shot 2018-08-01 at 10 10 52 pm" src="https://user-images.githubusercontent.com/3488986/43558492-cd467e5c-95d7-11e8-8f47-0e31ca61caf3.png">

<img width="408" alt="screen shot 2018-08-01 at 10 18 57 pm" src="https://user-images.githubusercontent.com/3488986/43558725-eb639932-95d8-11e8-845d-78b76c591ca9.png">

- [x] In the above mockup, the "X" button in the top left takes the user back to the page they were on when they opened the contact, so either the main register page or the woman's profile view. There should be a confirmation message first, informing the health worker that any data she entered will be lost and ask her to confirm or cancel.

- [x] The exact content and logic for the Quick Check form should come from the data dictionary, Quick Check tab, not from the mockups in this issue.

- [x] Note that the user cannot move past the Quick Check page until all required questions are answered.

- [x] If no danger signs are selected, they can "Proceed to normal contact" whereby they land on the main contact screen (https://github.com/OpenSRP/opensrp-client-anc/issues/42).

- [x] If a danger sign is selected, their options change, and they can either proceed to normal contact or skip the contact and go directly to the contact summary view (issue to be created). See below mockup.

<img width="404" alt="screen shot 2018-08-01 at 10 22 04 pm" src="https://user-images.githubusercontent.com/3488986/43558832-624aa252-95d9-11e8-9c65-119dffcac283.png">

- [x] If they select "Refer and close contact" they land on the below popup before they go to the contact summary view.

<img width="425" alt="screen shot 2018-08-01 at 10 22 48 pm" src="https://user-images.githubusercontent.com/3488986/43558882-926d4bf6-95d9-11e8-9349-24743f362cd1.png">

**Comment by cagulas** [comment]
QA results from 23 August 2018 build:

- [ ] There should be a confirmation message first, informing the health worker that any data she entered will be lost and ask her to confirm or cancel. **CG: I'm not seeing this yet**
- [ ] Specific complaint shouldn't be a required field

**Comment by rowo** [comment]
Looked at the latest build. 

This is a bit of an odd duck compared to the other contact form sections since it's almost a full screen dialog except there is one more option than the standard save and cancel choices. So maybe I can suggest additional requirements:

- [ ] The "Proceed to Normal Contact" button shouldn't show up until "None" is selected in the danger signs. 
- [ ] Can we add a line above the buttons that appear fixed at the bottom when they appear? Like this:
  <img width="417" alt="screen shot 2018-08-26 at 11 31 31 pm" src="https://user-images.githubusercontent.com/1584163/44639133-4995ca80-a988-11e8-9b68-1a4387e15059.png">
- [ ] The top bar should probably be fixed at the top
- [ ] The specify text input line needs to be more associated with the "specify other" (complaint) selection. This can be next to or underneath but at the same indent like this:
  ![screenshot_20180826-233704](https://user-images.githubusercontent.com/1584163/44639459-02103e00-a98a-11e8-8258-1c06eb325481.png)
- [ ] The interaction on the text input on the "specify other" is a bit funny since the text input box looks active but the keyboard isn't up until you click it again. Perhaps we could always show the specify other text input line and tapping the line makes the checkbox checked and the keyboard activated. If you just check the checkbox the line appears but it's not active (so the line should be grey). I'm also not a huge fan of the redundant "specify" words. Perhaps it could be removed from the label and other appear on the text input line.

**Comment by cagulas** [comment]
QA 11th Oct build:

- [ ] When you check "Other" for specific complaints, the Specify text box shows as active but the keyboard isn't activated. Can we activate the keyboard as soon as we check "Other"?
- [ ] Similarly, as Roger suggested above, if the user bypasses the "Other" and directly clicks on the Specify text input line, the "Other" checkbox should automatically get checked.
- [ ] Once you save the quick check form and proceed to normal contact, and if you go back to the quick check container again, the top left X should change into the contact containers icon. This is because once they proceed to normal contact, they have officially started the contact, so exiting the contact from that point asks them to save the contact (orange button state on the main register page) or exit and lose all data entered so far.

**Comment by rowo** [comment]
Here's a clarification for my "Other" question comment:

### Solution option 1
The fastest/easiest thing to do (I am guessing) would be to leave it as is. I think it is satisfactory but not ideal since the line looks active but you actually have to click to open the keyboard.

### Solution option 2
Make the text input inactived, as shown below with the specify text and required icon, so you tap to engage:
<img src="https://user-images.githubusercontent.com/1584163/46822517-b529d080-cd59-11e8-83da-f7ab70057e0b.png" width="280">

### Solution option 3
Open the keyboard + activate specify text input line when the "Other" checkbox is checked by the user. Since specifying is required, this saves a step. Problem is I don't know if it's always required.

### Solution option 4
Always make the Specify line appear so it looks like A or B below. If you clicked the checkbox, it would behave like an upgraded "Solution Option 2" where in addition to clicking the checkbox, you could just click the specify input which would both check the checkbox and start you with the keyboard open to start entering text.
<img src="https://user-images.githubusercontent.com/1584163/46822211-db9b3c00-cd58-11e8-8162-4da244a516f2.png" width="280">

**Comment by rowo** [comment]
@ellykits @ndegwamartin @cagulas 

Regarding how to handle "Other", let's just do solution 2 from above... "Other" is a checkbox. If a specify is needed, a box appears. If the specify is required, it gets an asterisk.

<img width="533" alt="artboard 235 copy" src="https://user-images.githubusercontent.com/1584163/47854390-00169100-ddb8-11e8-8d79-80c5f718fee9.png">

**Comment by ndegwamartin** [comment]
cool @rowo

**Comment by ndegwamartin** [comment]
Could we leave the hint as asterisk as grey since it inherits the hit color?

**Comment by rowo** [comment]
@ndegwamartin I think the color goes a long way for consistency, so as an alternative, would it be easier, for keeping the red color, to put the asterisk outside the box like in https://github.com/OpenSRP/opensrp-client-anc/issues/40#issuecomment-429048197?

**Comment by ndegwamartin** [comment]
yeah that would be far much easier 👍

**Comment by ellykits** [comment]
@rowo Yea putting the asterisk outside the box will be easier

**Comment by cagulas** [comment]
QA 14th Dec 2018:

- [ ] The Quick Check should be launched first, no matter where the contact is first initiated. Right now, if the contact is opened from the main register page, the Quick Check page is skipped and the user goes straight to the main contact page. They should always land on the quick check page first.
- [ ] If they tap the top left X when they first land on the page, and they confirm close, they should go back to the main register page and NOT the contact page. This is the first time they are opening the Quick Check page, so allowing them to exit out to the main register page before they really get into the contact workflow is important, in the case of accidental clicks. However, if they proceed to the normal contact then go back to the quick check, then they shouldn't have the top left exit out button anymore.

**Comment by cagulas** [comment]
Closing this and putting final, remaining QA in a new issue.
