### ISSUE TITLE
Implement Workflow for post-registration

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#403]
Updates:
- [x] 1. Immediately after the registration form is saved, it should go to the profile of the person that was just created.
- [ ] 2. This profile needs to be updated so the button of the contact appears at the bottom. Currently, the button appears below the fold even though there is no data for that person pushing the content down.
- [x] 3. This empty state should include instructional text and an arrow to indicate the next step: https://marvelapp.com/9j1277a/screen/63920582/handoff

**Comment by dubdabasoduba** [comment]
@cafootitt   For point number `2`, this happens because of the folding toolbar we are using. It kinda extends the height of the page so anything that supposed to be shown at the bottom of the screen will be only be shown after the toolbar folds. I am still researching on a better way to implement it.

**Comment by cafootitt** [comment]
Thanks for the advance heads up before I started QA'ing!

**Comment by cafootitt** [comment]
1 and 3 pass QA. I'll move #2 to a new issue.
