### ISSUE TITLE
Upgrade server version

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#466]
Server update: 
        * https://github.com/OpenSRP/opensrp-server-web/pull/203
        * https://github.com/OpenSRP/opensrp-server-core/pull/136
        - Need to deploy v1.6.4-SNAPSHOT

**Comment by cafootitt** [comment]
QA steps to follow:

Create event
Sync
Go offline
Edit event
Go online, sync
See if another device gets the edit

- ANC Registration form
- 5-10 minutes LOE for the server upgrade

**Comment by dubdabasoduba** [comment]
Now that we need to use OpenSRP web for the Population Characteristics we need to do the following

- [ ] Enable Oauth on our server instances. The reveal team can helps us in configuring this.

- [ ] Figure out how to use the new  `/location/by-level-and-tags` added by the  Health Facility harmonizaiton team to get locations since OpenSRP web does not use OpenMRS locations.

@ellykits Does this end point return a hierarchy or it lust returns a list of locations?

**Comment by ellykits** [comment]
The endpoint returns a list of locations.

**Comment by vincent-karuri** [comment]
Done, deployed `v1.7.0-SNAPSHOT` at https://anc-stage.smartregister.org/opensrp/.

**Comment by cafootitt** [comment]
V1.2.14 - lgtm. 

Thanks @AnnieMungai for the assistance on the QA.
