### ISSUE TITLE
Implement Profile contact container on subsequent contacts [To Be Replaced]

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#51]
**UPDATED 11 Sep 2018: Please see last comment. Initially, we aren't going to do full section edits — we will only do single question edits and treat it consistently everywhere. We will replace this issue with a new one.**

The Profile contact container is a bit different from the rest, in that all the questions in this section are for first contact only. This means that in subsequent contacts, the Profile section can be formatted differently, allowing the user to review the answers on a single screen and make edits if required:

<img src="https://user-images.githubusercontent.com/1584163/44436211-f71c6e80-a581-11e8-9393-878247696386.png" width="400">

- [ ] Sections are clearly defined
- [ ] Tapping Edit for any section opens up that section in an edit dialog (see below). Tapping X goes back to Profile container without changes. Tapping save saves all the changes for that section and takes user back to Profile container.

<img src="https://user-images.githubusercontent.com/3488986/44254928-fba4f800-a20c-11e8-9556-8bddc85a50e2.png" width="400">

**Comment by rowo** [comment]
@cagulas @ndegwamartin related to https://github.com/OpenSRP/opensrp-client-anc/issues/74; I'm trying to figure out a consistent way to handle the subsequent contacts with mix first/all contact questions. Would welcome your thoughts and reactions to the below thought sequence so far:

1. For the profile, since no questions need to be answered again, it makes a lot of sense to do the summary view as seen in this issue. 
2. Something like Physical Exam > Weight & Height has a mix of first/all contacts. So the first contact might look like this when blank and filled in:
  <img src="https://user-images.githubusercontent.com/1584163/44674557-e6458000-a9fb-11e8-8809-350a05200f68.png" width="300"><img src="https://user-images.githubusercontent.com/1584163/44674558-e6458000-a9fb-11e8-92a9-99e767d193a3.png" width="300">
3. The easiest way to handle the subsequent contacts situation is probably to just pre-fill in the answered questions. However, the required questions might get lost and it'd be pretty inconsistent with the Profile section
4. Another option would be to insert unanswered questions into the summary view where appropriate. I do not have a mockup of this. However, I do have a mockup of keeping the separate sections while inserting the unanswered questions:
  <img src="https://user-images.githubusercontent.com/1584163/44674797-9f0bbf00-a9fc-11e8-9b51-f2218be3f1b1.png" width="300"><img src="https://user-images.githubusercontent.com/1584163/44674798-9f0bbf00-a9fc-11e8-924c-8fec741203be.png" width="300">
5. One issue is it's not a consistent approach from the Profile section. If we were to make it consistent, on subsequent contacts the Profile section would look like this:
  ![profile-secondcontact](https://user-images.githubusercontent.com/1584163/44674872-daa68900-a9fc-11e8-9b8b-03d44c6f810d.png)

**Comment by cagulas** [comment]
@ndegwamartin @keymane and @dubdabasoduba Please weigh in here. I like this approach and since we haven't implemented profile contact container yet, maybe we can switch that approach to what's shown here as well. I am getting slightly concerned about increasing scope for the form library though, so please weigh in honestly with what you think is achievable and realistic to implement.

**Comment by keymane** [comment]
@rowo Having separate sections is a good idea but will definitely affect the time we spend refactoring the form library. Adding an Edit dialog form in another form may be a bit tricky. Also implementing the logic for separating the form from the summary view may take time.

Is it possible to change 'Previous Responses' to 'First Contact only' or 'Summary..' because we may not provide a list of all the responses for a particular question.

**Comment by rowo** [comment]
Update from offline chat with @cagulas and @keymane : 
- We will show all form fields, but fields that are "first contact only" will be in an uneditable state with an edit button. 
- If the edit button is clicked, the field becomes editable and the user can change the value
- The new value for the field is submitted along with the rest of the form
- Initially, all "first contact only" questions will be treated this way, including the profile section. We can circle back to do the "full section edits" at a later time.

**Comment by cagulas** [comment]
Replaced with https://github.com/OpenSRP/opensrp-client-anc/issues/149
