### ISSUE TITLE
Release files for previous releases get overridden with the updated release files

### ISSUE THREAD

**Issue by cafootitt** [opensrp/opensrp-client-anc#552]
Steps to replicate:

- Download files for the latest release (let's say it's V0.0.3)
- Make changes to the files and make a new release (V0.0.4)
- If you download the files again for the V0.0.3 release, you'll notice they are also updated with the files changed in the 0.0.4 release. You'd expect the files to remain the 0.0.3 versions.

**Comment by dubdabasoduba** [comment]
- [ ] When downloading we give you the latest form so as to make sure you do not overwrite the changes made earlier by someones else. That's why v0.0.3 also gave you the latest form

**Comment by cafootitt** [comment]
@dubdabasoduba But the user would just download v0.0.4 forms to get the latest version (in this scenario), so I don't see why 0.0.3, 0.0.2, 0.0.1 versions also get updated with 0.0.4 version. You'd want the previous versions to remain the same.

**Comment by rehammuzzamil** [comment]
@dubdabasoduba Can you please brief me about this issue?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba Can you please brief me about this issue?

**User story**
- Update a form. let's give this form the version number `v1.2.0` and name it `add_user.json`
- Make a release. let's give this release version number `v1.2.0`

- Update the form `add_user.json` now the form version will be `v1.2.1`
- make a release. This new release will be version `v1.2.1`

- Open release `v1.2.0` and view the files. You will notice `add_user,json` is marked as version `v1.2.1` instead of `v1.2.0`. Now try to download the file. You will get the download `v1.2.1` instead of `v1.2.0`
