### ISSUE TITLE
Implement HIV test result workflow

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#60]
An HIV test is due at the first contact and again at the first contact of 3rd trimester (GA 28 weeks) if the woman isn't already confirmed HIV+ and only in settings where the population prevalence is 5% of higher. After the initial HIV test is done, then the HIV test should be available in the Other optional tests section in all future contacts, until it becomes due again at the beginning of 3rd trimester. If woman is confirmed HIV+ at any point in pregnancy, then HIV test does not need to be shown at all in Tests contact container.

See data dictionary, Tests tab, HIV section, for content.

**Comment by cagulas** [comment]
QA 29th March release:

- [ ] Double required asterisk shows on HIV test date
- [ ] HIV test date shouldn't be shown if Done today selected
- [ ] Rows 71 and 77 (pink highlighting) in the data dictionary need to be addressed.

**Comment by cagulas** [comment]
18th April release:

- [ ] The above items were fixed, but now for some reason, HIV positive counseling shows, even if the woman is HIV negative, see below.

This might be because I had originally said the woman was HIV positive in prior medical conditions question in Profile, but I went back to change it, but still in the HIV test result, it's preemptively showing HIV positive counseling, and still shows HIV positive counseling when I enter negative.

![Screenshot_20190419-114402](https://user-images.githubusercontent.com/3488986/56416286-10a0c200-6299-11e9-96f6-0dc90e9abf93.png)

**Comment by cagulas** [comment]
HIV schedule still not working. When I fast forward to 29 weeks gestational age by adjusting device date/time settings, HIV test does not show up in Due when it should.

**Comment by hmakandi** [comment]
SCN01: First Contact with negative result Pwanitwi Kwanitwi  ->HIV test showed, record done. Results displayed under contact. OK
SCN02: First Contact with positive result: Pretatwi Kwetatwi, ->HIV test showed, record done, Results displayed under contact. OK
SCN03: First Contact with no test/result: Pidut Kwidut,->HIV test showed, no record done, No Results displayed under contact. OK
SCN04: <29 Weeks for Pwanitwi Kwanitwi , -> Date Set at 15/07. GA 20 Weeks No tests shown under Due. All tests are under Other including HIV(Container shows 64 required fields). OK*
SCN05:<29 Weeks for Pretatwi Kwetatwi,->At 21 Weeks no HIV test showed. Record of previous test exists under contact details as positve. OK
SCN06:<29 Weeks for Pidut Kwidut,->GA 32 Weeks. HIV test showed. OK
SCN 07: >=29 Weeks for Pwanitwi Kwanitwi,->Set Date to 15/10. GA 34 Weeks,HIV test shows on Other(Next) tab. OK
SCN08: >=29 Weeks for Pretatwi Kwetatwi, GA 34 weeks HIV test not shown OK
SCN09: >=29 Weeks for Pidut Kwidut, Set date 15/08S HIV test showed. OK

Bug/Issues:
*Can be confusing having due empty, and user is expected to click next...

Other observations:
-Performance issue with the test form, sometimes it keeps refreshing, sometimes it does not store the record
-UI consideration to have the submit button on top of tests form, rather than next then submit. The test record data disappears on save if you had not clicked this submit.

**Comment by hmakandi** [comment]
@rowo -UI consideration to have the submit button on top of tests result form, rather than next then submit.

**Comment by rowo** [comment]
@hmakandi This happens in all of the contact containers, so if it changes in tests, it should change everywhere for consistency. The reasons it's at the on the last page are:
- This is new to me or maybe didn't realize what this change meant if it was brought up. The designs had a "Done" button who's purpose was just to move the user back to the Contact menu, but I didn't think anything was required to save data. In my mind a contact was one big single form.
- There is a hamburger menu that's supposed to go into the top right. I'm not sure if this is still in scope? It is not in the app in the latest apk.

That being said, I agree this would be an improvement if we're not doing that hamburger menu (who would know that?). A save button would need to always be active even if not all required fields were complete.
