### ISSUE TITLE
Implement syphilis test result flow

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#64]
A syphilis test is due for all pregnant women who are not already confirmed positive for syphilis at the first contact and again at the first contact of 3rd trimester (GA 28 weeks) if negative at the first test. After a negative test, the syphilis test should be available as an optional test in the Other Tests section.

Similar to Hep B, Hep C, and urine test, there are 3 different types of syphilis tests to choose from. 

See data dictionary, Tests tab, Syphilis section for exact content and logic.

**Comment by cagulas** [comment]
@ellykits I'm unable to test this, because I can't find a case who has syphilis test due. It should be due at first contact for all women, so let's check the due logic first.

**Comment by cagulas** [comment]
18 April release:

- [ ] The follow-up test at 29 weeks is not working yet. I registered a woman, Louisa May, and her first syphilis test was negative at 22 weeks GA. I changed the device date/time settings to be 7 weeks in the future, so she's 29 weeks GA, but syphilis test does not appear in Due like it should.
- [ ] In the above scenario, syphilis test didn't even show up in the Other tab. Let's double-check that as well, because the test, if it's not currently due, should show up in the Other tab (if the woman is not already tested positive).

**Comment by ellykits** [comment]
We had an issue of loading global values from other contact containers in the current visit (will sort this issue as soon as we resume). Try opening profile container then navigate to **current pregnancy** section then leave the form. Now load Test Container check if the logic works. Again, this is a bug we noticed later and will resolve it before the next release.

**Comment by cagulas** [comment]
Syphilis schedule still not working. When I fast forward to 29 weeks gestational age by adjusting device date/time settings, syphilis test does not show up in Due when it should.

**Comment by hmakandi** [comment]
SCN01: First Contact with negative result: Pula Wula, ->Syphilis test showed, record done. Results displayed under contact. OK
SCN02: First Contact with positive result: Puka Wuka, ->Syphilis test showed, record done, Results displayed under contact. OK
SCN03: First Contact with no test/result: Pufa,Wufa,->Syphilis test showed, no record done, No Results displayed under contact. OK
SCN04: <29 Weeks for  Pula Wula, -> Date Set at 15/07. At 25 Weeks no Syphilis test showed. Record of previous exists under contacts.OK
SCN05:<29 Weeks for Puka Wuka,->At 25 Weeks no Syphilis test showed. Record of previous test exists under contact details. OK
SCN06:<29 Weeks for Pufa,Wufa,->Could not establish GA, still indicates First Contact is due. Quick Check and Profile was complete. Syphilis Test Showed. NOK**Needs more information to conclude.
SCN 07: >=29 Weeks for  Pula Wula,->Set Date to 15/10. GA 33 Weeks,Previous Syphilis record shows, No syphilis test showed. NOK **Confirm if it is expected behaviour
SCN08: >=29 Weeks for Puka Wuka,GA  Could not establish GA, Shows contact 2 is due, No syphilis test showed. NOK**Confirm if it is expected behaviour
SCN09: >=29 Weeks for Pufa,Wufa, Shows contact 1 is due, could not calculate GA. Syphilis test showed. OK

Bug/Issues:
-The GA calculation needs to be looked at for Pufa and Puka
-Syphilis test should still show for Pula despite the negative result?

Other observations:
-If first contact is already closed and it is second contact which is due, why do we display the option for First contact when doing quick Check?
-Maybe an info box to suggest what is needed to close a first contact/second contact etc?

**Comment by hmakandi** [comment]
Cleared data on phone which resolved GA calculation issue. Needs further checks to confirm what went wrong.

SCN06:<29 Weeks for Pufa,Wufa,->Set date 15/07 GA 20 weeks. Syphilis test did not show. OK
SCN 07: >=29 Weeks for Pula Wula,->Set date 15/10 GA 33 Weeks, Syphilis test shows, Could not confirm recording of new results due to data issues from saving the info. OK.
SCN08: >=29 Weeks for Puka Wuka,->Set date 15/10 GA 39 Weeks, Shows contact 2 is due, No syphilis test showed. Confirmed as expected behaviour due to +ve first contact result. OK
