### ISSUE TITLE
Update logic on fetal heartbeat

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#665]
### Feature Use Case

Update logic on fetal heartbeat, the gestational age is < 12 weeks and no fetal heart beat is present, this is not a red flag. In some places, depending on the device available, the health worker only can register the FHB after 20 weeks. Should only trigger the flag when GA is > 20 weeks AND no FHB detected.

### Acceptance criteria

Should only trigger the flag when GA is > 20 weeks AND no FHB detected.
Move the gestational period from 20 weeks to 12 weeks

**Comment by Naima-Bashir** [comment]
Some comments from @TigestT : Should only trigger the flag when GA is > 20 weeks AND no FHB detected.
Move the gestational period from 20 weeks to 12 weeks—this is similar to the  with the first comment. I think the originally flag was triggered when GA was 12 weeks and it should instead be >20 weeks.

@shoaibmushtaq25 , kindly see the above comment.

**Comment by Mstjamush** [comment]
FHB still being flagged at 12 weeks

**Comment by Naima-Bashir** [comment]
@junaidwarsivd  kindly change this to >20 weeks

**Comment by junaidwarsivd** [comment]
@Mstjamush  could you please share the screenshot where the issue is occured because i've checked on the same apk with the woman having gestational age 12 week and the fetal heart beat is not being flagged cc @Naima-Bashir 
![Screenshot_1637054736](https://user-images.githubusercontent.com/81764603/141959192-a32f2c17-be71-4d66-accd-454a2dcde6e1.png)
patient profile : sunday baby
