### ISSUE TITLE
Reporting dashboard

### ISSUE THREAD

**Issue by imukunzi** [opensrp/opensrp-client-anc#731]
### Feature Use Case

Displaying data collected from ANC client

### Acceptance criteria

Graphics table including submitted data from anc and selection function

The dashboard to enable project managers to generate report based on location, period and health condition. Report will be generated to health facility level,district, and national level.

### Project Contact

Innocent Mukunzi

### Relevant Information

This feature will help on administration level  select specific data based on different criterials such as district health center, health condition of patient etc.

**Comment by Naima-Bashir** [comment]
@imukunzi What type of dashboard are you guys developing, who are the users, what tools are you going to use, what do you need help with, and what are the expected time frames? That ticket is way too broad and vague.

**Comment by Naima-Bashir** [comment]
@imukunzi met with the local partners to discuss the dashboard. They also did an upgrade and the services didn't happen as expected : https://github.com/opensrp/web/issues/898 . @machariamuguku will pair with the the client and support them.
Due to upcoming holidays, the reporting dashboard ticket will be picked up in January (after the holidays) cc @dubdabasoduba

**Comment by Naima-Bashir** [comment]
Reporting Dashboard Document with the questions/ requirements needed in order for the work to begin can be found here: https://docs.google.com/document/d/1E-Tw8YaPc6BZlrXRUy2Z9ibYsIxtRGHWnGF54tE48ds/edit
