### ISSUE TITLE
[Ona Support Request]: Getting error while installing  postgres for  Server in kubernetes.

### ISSUE THREAD

**Issue by khadkadipesh** [opensrp/opensrp-client-anc#781]
### Affected App or Server Version

Client anc 1.6.10 App version

### What kind of support do you need?

Install postgres successfully in AWS.

### What is the acceptance criteria for your support request?

Postgres should get running without any issues and be able to create database, users etc. without any issues in server.

### Relevant Information

psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

Following document was followed while installing:
https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/2909995009/How+To+Setup+Opensrp+Server+Web+on+Kubernetes

**Comment by bennsimon** [comment]
@khadkadipesh Thanks for raising this. So Bitnami postgesql helm chart was upgraded recently. I have updated the documentation accordingly. The changes that affected your deployment is that the postgres password config was changed from `postgresqlPassword` to `auth.postgresPassword` and database name config was changed from `postgresqlDatabase` to `auth.database`.

Since you have already deployed, a password was automatically generated for postgres user, you can get the postgres password by 
```shell
kubectl get secret --namespace default postgres-postgresql -o jsonpath="{.data.postgres-password}" | base64 --decode
``` 
and then continue with the rest of the documentation.

**Comment by Naima-Bashir** [comment]
pair session happened today

**Comment by Naima-Bashir** [comment]
Nepal team to go through the Documentation and follow it. 
Install keycloack 
Ona and @bennsimon to discus with SRE team to get KOPS documentation

**Comment by Naima-Bashir** [comment]
Updates from today's pairing session:
The Ona team is taking the Nepal team through Docker. 
They have resolved to using docker as an alternative as they have minimal resources for now to support a Kubernetes deployment
