### ISSUE TITLE
Tasks under overview not populaing after contact

### ISSUE THREAD

**Issue by MwambaK** [opensrp/opensrp-client-anc#793]
### Affected App or Server Version

v1.6.8

### What kind of support do you need?

we need assistance figuring out why the tasks on the overview page are not populating

### What is the acceptance criteria for your support request?

tasks that are not done or ordered should be visible and accessible on the overview page

**Comment by dubdabasoduba** [comment]
Please add a title to this issue

**Comment by Naima-Bashir** [comment]
@MwambaK we cannot replicate this from our end as it works as expected. Kindly send us an apk from your end with the bug. 
cc @dubdabasoduba @junaidwarsivd

**Comment by madrinekariuki** [comment]
@Naima-Bashir using the apk shared [Here](https://opensrp.slack.com/archives/C92GVBDU7/p1647329875876759?thread_ts=1646824966.614339&cid=C92GVBDU7)
user :`anc`
- I am getting the error shown in the screenshot below when trying to open the tests form and once I complete the contact the tasks form on overview is empty. 
- could the error on the tests form be the cause since there is no recorded test?.
- Also notice how the general app overview is different and some forms not opening
![image](https://user-images.githubusercontent.com/84722169/158357646-aedc4efc-0315-4a4c-b42a-debb90f59c71.png)
