### ISSUE TITLE
Attention flags mismatch

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#811]
### How do we replicate the bug?

The optiBP apk 1.6.12 apk on client Gia Homu who has 5 attention flags but when you count they are 6.

The attention flags are still not updating
attention flags are not counting correctly we have 3 its showing 2 on the homepage for Halsey heiley and for Julie Mu its showing 6 but we have 3.
Attention flags are showing as a path.
Tests are not appearing on the attention flags. added HIV +ve, Hep B +ve, syphillis +ve for Halsey heiley `
![image](https://user-images.githubusercontent.com/61143692/161496928-c984335a-b763-4bab-a575-ee7e8ff14c52.png)

### How is this feature expected to work?

The attention flags should update correctly

**Comment by madrinekariuki** [comment]
@junaidwarsivd 

Kindly note this issue is still persistent  on this shared [apk](https://onaio.slack.com/archives/CETQ18XL3/p1650899294306949?thread_ts=1650871117.072899&cid=CETQ18XL3). 
- see the attention flag details for clients `Janet gavi `and `Becky Kenya`
- both show the number of attention flags as 8 but when you do a manual count it is 7 on both.
