### ISSUE TITLE
Adding support for android 11 and 12

### ISSUE THREAD

**Issue by dodosi** [opensrp/opensrp-client-anc#845]
### Affected App or Server Version

v1.6.14

### What kind of support do you need?

Android 12 is not having devices back buttons. It makes it difficult for user to navigate backwards.

### What is the acceptance criteria for your support request?

Seeing application buttons that can assist the user to naviate backwards

### Relevant Information

![image](https://user-images.githubusercontent.com/8068177/170510719-a048d9d9-562b-434c-9bd7-2e3d132e8dff.png)
**The highlighted buttons cannot be found on android 12 device below.**
![image](https://user-images.githubusercontent.com/8068177/170511133-e8c5634c-54d5-4ed9-9c96-73028a505339.png)

**Comment by AngelaKabari** [comment]
Thanks for raising this issue @dodosi. While it is in the product roadmap to update all the OpenSRP libraries that WHO ANC uses to ensure that they are compatible with Android 11 and 12, this will not happen in time for the launch of the Rwanda version of the WHO-ANC app. As such, we would like to suggest the following workarounds in the meantime:

1. Android 10 and higher allows users to re-enable the back button. Please see [this article](https://support.google.com/android/answer/9079644?hl=en) that provides instructions on how to do so.
2. In this particular deployment of the ANC app for the IR study, the app will be used only in a controlled situation. In case the specific devices the Rwanda team is using for this study do not allow for the fix in 1 above to be implemented, a pragmatic and non-technical solution, could be taking some time in the user training sessions to show your users how to navigate the app in Android 11 and 12 in the absence of the back button. This can also be included in the training materials so that they can refer to it should they have any issues after the training.

**Comment by dubdabasoduba** [comment]
@dodosi How much priority is this support addition for the Rwanda launch?
