### ISSUE TITLE
[Ona Support Request]: Modify site characteristics

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#849]
### Affected App or Server Version

Indonesia local apk

### What kind of support do you need?

The client app shows multiple same questions about the site characteristics.  SID team needs support on how to fix this
https://drive.google.com/file/d/1-DsXofoInc8wBPpIldG3r4EhdFYlwU9C/view

### What is the acceptance criteria for your support request?

The client app doesn't show multiple same questions about the site characteristics.

**Comment by madrinekariuki** [comment]
@SebaMutuku 
test device: `samsung A12 android 11`
app:[ reference-app-release-location_issues.apk](https://onaio.slack.com/archives/C0E2558SH/p1660303459232079)

steps:

- install the app and sync data.
- click on `me` section
- click on site characteristics. (first confirm we have data here)
- click on edit, edit some of the questions and click save.
- check the site characteristics again and observe the questions did not change


observations:
- when you click on site characteristics we have data. 
-  when you click on edit and change some answers on the questions, you will observe that after saving the data is not changing.

**Comment by madrinekariuki** [comment]
The issue on editing the form is related to the issue on Radio buttons and is being worked on under #856

**Comment by ariadng** [comment]
@AngelaKabari has this issue already been fixed?

**Comment by AngelaKabari** [comment]
@ariadng Yes, the original issue #849, that is, the client app not showing multiple same questions about the site characteristics, has been fixed. 

Thereafter, the Zambia team noted that Native Form Version 2.1.19 was occasionally not updating radio buttons, and raised issue #856. We addressed this for the forms in the six containers, and thus we were able to close this issue for Zambia. 

However, in the process of QA-ing issue #849, we noted that the radio buttons were not updating in the site characteristics form, and thus re-opened #856. We then realised that the issue #856 was not accurately representing the bug, which is why we opened issue #883. 

We have not yet gotten around to addressing [issue #883](https://github.com/opensrp/opensrp-client-anc/issues/883), as there were more urgent issues to resolve. However, since this is now presenting a problem for the SL@B project, I have updated the issue on Github accordingly. That is, I’ve changed this issue from medium to high priority, and added it to the OptiBp <> WHO ANC integration project

@Naima Bashir will assign an engineer to it on Monday and be able to give you a timeframe for the fix thereafter.

**Comment by ariadng** [comment]
@AngelaKabari thank you for your response. Can you provide the link to PR/commits to fix the #849 issue?

**Comment by AngelaKabari** [comment]
Hello @ariadng,  

Here you go: https://github.com/sid-indonesia/opensrp-client-anc/pull/17

Cc @SebaMutuku and @Naima-Bashir

**Comment by ariadng** [comment]
Hello @AngelaKabari,

I'm sorry but this is the one that we already merged into the Bunda app for location fix. Isn't this issue #849 is about site characteristics?

**Comment by SebaMutuku** [comment]
@ariadng are the site characteristics on the app?

**Comment by Naima-Bashir** [comment]
Closing this with client approval
