### ISSUE TITLE
[Ona Support Request]: Add manual encounter date to existing scheduling logic

### ISSUE THREAD

**Issue by alfiraratnamalinda** [opensrp/opensrp-client-anc#919]
### Affected App or Server Version

v1.6.14

### What kind of support do you need?

We need to add the manually inputted encounter date to the existing next contact date scheduling logic and other logic that is directly dependent to the encounter date.

This link shows the changes that has been done by our tech team:
https://github.com/sid-indonesia/opensrp-client-anc/commit/4b0418de21640139567c307d1f186e0a5c5f5926

### What is the acceptance criteria for your support request?

To merge the encouter date with scheduling logic of the anc app

**Comment by Naima-Bashir** [comment]
The SID team had asked Ona for the file in the project that handles the next encounter schedule logic so that they can provide the fix required to accommodate both automatic and manual encounter date. I then shared the following links related to contact scheduling:
https://github.com/opensrp/opensrp-client-anc/blob/master/opensrp-anc/src/main/assets/rule/contact-rules.yml
https://github.com/opensrp/opensrp-client-anc/blob/master/opensrp-anc/src/main/java/org/smartregister/anc/library/interactor/ContactInteractor.java
https://github.com/opensrp/opensrp-client-anc/blob/master/opensrp-anc/src/main/java/org/smartregister/anc/library/helper/AncRulesEngineHelper.java

**Comment by dubdabasoduba** [comment]
@Naima-Bashir @alfiraratnamalinda the next contact date is not controlled by the EDD which is calculated during the first contact. It can obviously be changed. 

I might be missing something but please feel free to explain why you feel the date of the encounter affects the next contact date.

**Comment by dubdabasoduba** [comment]
https://github.com/opensrp/opensrp-client-anc/blob/696c5d8eadca3c1f3a94632c5d3982e081864191/opensrp-anc/src/main/java/org/smartregister/anc/library/interactor/ContactInteractor.java#L257-L260

**Comment by Naima-Bashir** [comment]
Updates: The SID team have confirmed that the changes implemented are working as expected. 
They found a bug in the their app that causes the next_contact data to be invalid. They are currently investigating it

**Comment by Naima-Bashir** [comment]
Issue can now be closed

**Comment by SebaMutuku** [comment]
SID still encountered issues:
1. GA using ultra-sound
2. GA using LMP
which was solved and shared an apk to SID QA to test.
