### ISSUE TITLE
Translation and punctuation issues

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-anc#955]
### Affected App or Server Version

indonesia-reference-v1.6.32.apk

### What kind of support do you need?

The following items nees to be translated/ punctuation needs to be fixed:

**PUNCTUATION, GRAMAR AND CAPITAL LETTERS**
1. sma should be SMA
2. Ingriss should be Inggris
3. Engliish should be English
4. ...

TRANSLATIONS:
When the App is in Bahasa:
1. Summary Page: Married is in English 
2. None is in English 
3. The Population Characteristics page is blank. When switched to English, it loads

### What is the acceptance criteria for your support request?

The app should be able to switch from English to Bahasa and vice versa

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir, please find the list [here](https://docs.google.com/spreadsheets/d/1CZOOVG5NVqr8XnYQyjfisHJfO8QEIyEX/edit?usp=sharing&ouid=104871085518893178803&rtpof=true&sd=true). I cannot write all the typos here because there are too many of them.

**Comment by mergygayatri** [comment]
@Naima-Bashir, could you please check whether this statement in the WHO-ANC app is correct
"Abnormal vaginal discharge (physiological) (foul smelling) (curd-like)". Thank you. 
![WhatsApp Image 2023-07-05 at 3 20 33 PM](https://github.com/opensrp/opensrp-client-anc/assets/119648701/d3b6e14d-0b61-4802-8598-3e0702a1f117)

**Comment by mergygayatri** [comment]
Also, could you please check what U/S stands for? 
"Rujuk untuk USG di fasilitas dengan peralatan U/S" 
Thank you @Naima-Bashir 
![Profil Rujuk u_s](https://github.com/opensrp/opensrp-client-anc/assets/119648701/38ce34d8-0dd0-4f25-a28a-e7bb07002638)

**Comment by Naima-Bashir** [comment]
Hi @mergygayatri Yes the "Abnormal vaginal discharge (physiological) (foul smelling) (curd-like)" in the Symptoms and Follow up page is correct. I have confirmed form the Data Dictionary and it is correctly written 
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/41650123-b159-4ee3-9e75-c45d79af93e2).

**Comment by Naima-Bashir** [comment]
As for the Ultrasound section , in the English apk; it says "Refer for ultrasound in facility with U/S equipment" when one clicks no on the Ultrasound tests. Perhaps you can tell us what Ultrasound is in Bahasa and we can replace it @mergygayatri 

Could you clarify where we can find the word _Engliish_  . We have not managed to find it

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir. Thank you. 
In Indonesia, we usually use USG for ultrasound. Then the correct translation is "Rujuk untuk USG di fasilitas kesehatan yang dilengkapi dengan USG" 

Then, the translation for 'Abnormal vaginal discharge (physiological) (foul smelling) (curd-like)' is 
Keputihan yang tidak normal (fisiologis) (berbau busuk) (seperti susu basi)

Thank you

**Comment by Naima-Bashir** [comment]
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/c156d80f-6dfd-4568-bc36-4bbd3130f0fd)

@hilpitome here is the screenshot

**Comment by Naima-Bashir** [comment]
QA feedback: reference-app-v1.6.34.apk
The following sections (radio buttons) are still untranslated:

1. Marriage status: Married is in English 
2. TTCV Immunization: 3 doses is in English 
3. Counselling section e.g use of condom and alcohol: Yes are both in English
4. Hadir pucat: Yes is in English 
5. Oedema: Yes is in English 
6. Type of Oedema: Ankle oedema, hands and feet oedema, lower back oedema are in English


![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/bdd60b64-9e1c-43f8-b8aa-a40c2bd95718)
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/17698011-f6bf-4a65-9eb0-ec1982db676d)
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/d53baa75-c183-41ad-8dbb-0fb48a6c0fb8)
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/c4a848dd-8f0a-4962-993d-80b05a332185)
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/92500eb6-91bb-4559-93fe-560bdbb69247)
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/ea0acde8-f08c-4606-89ef-87dc12f55777)

**Comment by hilpitome** [comment]
Fix for the issues shown was done in this [PR](https://github.com/sid-indonesia/opensrp-client-anc/pull/31/). The problem was that the relvance values which are mostly in english were being used for display. This was primarily a problem when the values are coming from radio buttons and checkboxes (More so when you answer with None, Don't Know, Yes and No). The fix for ensuring we have the proper values in the facts map was done [here](https://github.com/sid-indonesia/opensrp-client-anc/blob/e0c19a4490f6da850f983ae0fb8f333d8665e207/opensrp-anc/src/main/java/org/smartregister/anc/library/task/LoadContactSummaryDataTask.java#L106C1-L110C58).

**Comment by mergygayatri** [comment]
Please fix this
it says Puske SMAs --> it should be Puskesmas
Please see[ the screenshot](https://drive.google.com/file/d/1UOWxtRZl4WC8feG-r0pgket-giVbOKaG/view?usp=drive_link)

**Comment by mergygayatri** [comment]
Other issues:
1. Login page: [Nama belakang should be username](https://drive.google.com/file/d/11z3GKJklvJkplntolvmJfHslbBzqlxyP/view?usp=sharing)
2. Blue box: ["Hp B negatif harap ikuti kebijakan nasional mengenai vaksin Hep B"](https://drive.google.com/file/d/11C6kNCCKLNl_FE2aYdMB5S_7ol6-_1fY/view?usp=sharing). Hp B should be Hepatitis B

**Comment by hilpitome** [comment]
**Documentation for population characteristics fix:** 
1. Uploading the population characteristics to the server
  - The problem was that only a single population charasteristic was being pulled from the backend. It was later discovered that for all records to be pulled from the backend, they had to be uploaded using the v1 endpoint. Documentation on how to use v1 and v2 for settings endpoints can be found [here](https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1765212165/How+to+interact+with+the+OpenSRP+settings+endpoint())
2. Clearing the population characteristics and uploading them in English and Bahasa to the server
  - The issue here was that the app was retrieving the population characteristics once during login and for the current local i.e population_characteristics-en for English or population_characteristics-in for Bahasa.
  - This was solved by a workaround [here](https://github.com/sid-indonesia/opensrp-client-anc/blob/7c4d36d12672739f900819e2e0467134b8ee3ead/opensrp-anc/src/main/java/org/smartregister/anc/library/task/FetchPopulationCharacteristicsTask.java#L43C1-L76C19). Whereby the missing population characteristic for the current locale is pulled from the server if the records do not exist in the db. This is done when you are viewing the characteristics in the me screen/megragment

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir, could you please reopen this ticket? Please see a list of translation and typing issue [here](https://docs.google.com/spreadsheets/d/1i3-5nlUY_z5anuhVTZz_9Hmh2PRv5Z64N2j8bwSVxJU/edit?usp=sharing). Thank you.
