### ISSUE TITLE
[Ona Support Request]: Fields for twins

### ISSUE THREAD

**Issue by mergygayatri** [OpenSRP/opensrp-client-anc#956]
### Affected App or Server Version

v1.6.32

### What kind of support do you need?

1. Please move the number of fetuses (jumlah janin) to below fundal height (Pengukuran Tinggi Fundus Uteri (TFU)). 
2. So, if the number of fetuses is more than one, the follow questions will appear for each fetus as written below:
- Can you hear the fetal heartbeat? (Detak jantung janin ada?)
- The heartbeat rate and/or (Detak jantung janin (kpm))
- Fetal movement (Gerak janin)
![WhatsApp Image 2023-07-07 at 11 14 24 AM](https://github.com/opensrp/opensrp-client-anc/assets/119648701/f4d4af78-c3d8-4b24-812f-bb5f713dc681)

Thank you

### What is the acceptance criteria for your support request?

The follow-up fields appear for each fetus. Thank you.

**Comment by junaidwarsivd** [comment]
in native form there is a widget to called repeating group but its might have two problems one is the embedded input field which will change the current no.of fetuses selector to input field also it is not tested with the relevances 
currently added the fields in the form tied by relevances but note their might be a drop in the form's performance since there is already too much data in the physical exam page

**Comment by mergygayatri** [comment]
Berat lahir (birth weight): wrong format and wrong constraint. This field should be in **numeric** format, and **up to 4 digits**. [Currently it only allows up to 2 digits.](https://drive.google.com/file/d/14JFH0C6KDZi0Cp3VVSr_R6y9SfQ3SiKV/view?usp=sharing)
