### ISSUE TITLE
The Site Characteristics selections show No even though one selects Yes 

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-anc#958]
### Affected App or Server Version

Latest apk

### What kind of support do you need?

At the beginning of the app, when one selects certain choices as Yes and continues to use the app; the Site Charactericts on the Me page show No.  

### What is the acceptance criteria for your support request?

The selections at the beginning should remain the same

**Comment by hamza-vd** [comment]
The missing site characteristics were added to the server. However, there is an issue on the server side which is replicating the added characteristics so many times. Also server has a limit to return 1000 characteristics at max in a single API call which is why some characteristics added are not being returned hence causing the **edit** functionality not to function as expected. This needs to be fixed from the server side in order to fully esolve the issue.

**Comment by Naima-Bashir** [comment]
@AngelaKabari to reach out to Sebastian for server side assistance to solve the issue where the the Site characteristics are showing in multiples.

**Comment by hilpitome** [comment]
I have checked the backend database. There are several repetitions of the site characteristics. This issue is related to this one we had before, https://github.com/opensrp/opensrp-client-anc/issues/937. I believe we initially had the right acceptance criteria but changed it. The thought at first was that, a user should only ever encounter the site characteristics when they login to the app for the first time. Then even if they clear the db or do a fresh install, they should not be prompted to fill in the site characteristics when they login. But we can confirm if this is the behavior experienced when using Ona's WHO ANC App cc @hamza-vd @Naima-Bashir @AngelaKabari @SebaMutuku

**Comment by SebaMutuku** [comment]
@Naima-Bashir @hilpitome  Is there a way we can try with a fresh user and see how this is happening?
