### ISSUE TITLE
Missing location upon log in

### ISSUE THREAD

**Issue by AngelaKabari** [OpenSRP/opensrp-client-anc#965]
### Affected App or Server Version

Latest apk (indonesia-reference-app-v1.6.39.apk) + OpenSRP Web v2.3.5

### What kind of support do you need?

When a user logs into the app, the app occasionally it shows on the "Welcome" page that the location that the user has been assigned to as null. Additionally, no location appears on the "Me" page.

### What is the acceptance criteria for your support request?

The app should display the correct location that the user has been assigned to on the "Welcome" page as well as on the "Me" page.

### Relevant Information

Nothing further

**Comment by hamza-vd** [comment]
The fix for this issue has been completed. There was a race condition where `LockingBackgroundTask` was locking the thread to execute. I have refactored the tasks to use `AsyncTasks` instead because, as per Google's documentation, all the `AsyncTasks` called will be executed in series, not in parallel, so it won't break anything.
