### ISSUE TITLE
[Ona Support Request]: Additional new fields

### ISSUE THREAD

**Issue by mergygayatri** [OpenSRP/opensrp-client-anc#969]
### Affected App or Server Version

v1.6.48

### What kind of support do you need?

Please add some new fields. You can see the dictionary [here](https://docs.google.com/spreadsheets/d/171Va6UfgqG9nOE4ATo1SGfXg8oE13Ra1/edit?usp=sharing&ouid=104871085518893178803&rtpof=true&sd=true).

### What is the acceptance criteria for your support request?

All the additional fields are added

**Comment by Naima-Bashir** [comment]
Ona and SID have agreed that this ticket is a new feature and not included in the current contract and timelines as it's out of scope

**Comment by Naima-Bashir** [comment]
**PROFILE PAGE:**

1. Add a section **Current Medical Information** after Past health conditions. A user should be able to select multiple options (check boxes):

- [x] Hypertension
- [x] Heart disease
- [x] Thyroid
- [x] Allergic
- [x] Auto immune
- [x] Diabetes
- [x] Asthma 
- [x] TB
- [x] Hepatitis B
- [x] Mental health issues
- [x] Syphilis

- [x] _This information should also be displayed in the Summary page_. 

**The choices made here should also reflect on the Counselling and Treatment section. E.g if one selects Diabetes, there should be a logic that is included in the C&T section.** 

2. Add a section - **Family member health history**  after the **Current Medical Information**  section. A user should be able to select multiple options (checkboxes):

- [x] Hypertension
- [x] Heart disease
- [x] Mental health issues
- [x] Diabetes
- [x] TB
- [x] Blood disorder
- [x] Asthma
- [x] Allergic reactions
- [x] Hepatitis B 
- [x] Other - text field for other

- [x] _This information should also be displayed in the Summary page_. 

**The choices made here should also reflect on the Counselling and Treatment section. E.g if one selects Diabetes, there should be a logic that is included in the C&T section.** 

3. In the TT vaccine section (profile section), when one selects **Under - immunized** , add a new field where one can select the type of TT vaccine (check boxes):

- [x] TT 1
- [x] TT 2
- [x] TT 3 
- [x] TT 4
- [x] TT 5

- [ ] _This information should also be displayed in the Summary page_. 

4. The Woman's Behavior section - after the Caffeine, Tobacco section, add a new filed: **History of risky behavior 1 month before pregnancy**. A user can select multiple options (checkbox):

- [x] Risky diet
- [x] Less Physical activity 
- [x] Teratogenic drugs (drugs that can cause defects in the fetus)
- [x] Cosmetics containing harmful substances
- [x] Environmental risks: pesticides/others
**There should be a logic that is reflected in the Counselling and Treatment section**

5. In the Obstetric History section - SID and Ona have agreed to leave as it is. This is because one can select the number of pregnancies, the number of pregnancies lost, number of live births and still births.
 
6.  In the Obstetric History section, when one selects more than 1 in the number of pregnancies (including this pregnancy), add the following fields:
- [x] Year - Integer
- [x] Birth weight (gram)
- [x] Delivery method
- Vaginal delivery
- Assisted vaginal delivery
- Ceserean
- [x] Birth attendant
- Family
- Traditional birth attendant
- Midwife
- Medical doctor
- Specialized doctor/ OB/GYN
- None
- Other- text field for other
- [x] Pregnancy complication
- None
- Dystocia
- Hypertension in pregnancy
- Postpartum hemorrhage
- Infection
- Maternal sepsis
- Preeclampsia
- Eclampsia
- Other- text field for other
7. After the Fetal Assessment section, add a section called **Special Examination/ Inspection**
- [x] Vulva
- Normal
- Abnormal
- [x] Urethra
- Normal
- Abnormal
- [x] Vagina
- Normal
- Abnormal
- [x] Fluxes
- Positive
- Negative
- [x] Flour
- Positive
- Negative
- [x] Porsio
- Normal
- Abnormal

- [x] _This information should also be displayed in the Summary page_. 

**PHYSICAL EXAM PAGE**

8. In the Physical Exam Page, after the **pallor present** section, add the following fields (_should be asked in the 1st and 4th Contacts_ ) but not mandatory:
- [x] Conjungtiva
- Normal
- Abnormal
- [x] Sclera
- Normal
- Abnormal
- [x] Skin
- Normal
- Abnormal
- [x] Neck
- Normal
- Abnormal
- [x] Tooth mouth
- Normal
- Abnormal
- [x] Ear, nose and throat
- Normal
- Abnormal

- [x] _This information should also be displayed in the Summary page_. 

9. In the Physical Exams Page, after the **Pelvic Exam** section, add the field:
- [x] Limbs
- Normal
- Abnormal

- [x] _This information should also be displayed in the Summary page_. 


**TESTS PAGE**
10. In the Tests Page, there is the Ultrasound Test section, after the number of fetuses; add the following field:

- Trimester 1
- Trimester 3 
 When one selects Trimester 1, add the following fields:

- [x] GS (Gestational Sac)
- [x] CRL (Crown-rump Length)
- [x] FHR (Fetal heart rate)
- [x] Location of the Gestational Sac
- Intrauterine
- Extra-uterine
- [x] Expected date of Delivery - Date

11. When one selects Trimester 3, show the following fields:

- [x] Fetus
- Alive
- Dead
- [x] Fetal location 
- Intrauterine
- Extra-uterine
- [ ]Fetal Presentation 
- Cephalic
- Pelvic
- Transverse
- Other - field
- [x] Fetal weight (gram)
- [x] Placenta location
- Praevia
- Low
- Anterior
- Posterior
- Right side
- Left side
- Fundal
- [x] BPD (cm) - integer (2 digits)
- [x] HC (cm) - integer (2 digits)
- [x] AC (cm) - integer (2 digits)
- [x] FL (cm) - integer (2 digits)
- [x] SPD amnion(cm) - integer (2 digits)
- [x] Gestational Age (week) - integer (2 digits)

- [x] _This information should also be displayed in the Summary page_. 

12. In the Urine Test section, add this field after the Urine dipstick section: **Reducing substances test** (mandatory): 

- [x] Negative
- [x] +
- [x] ++
- [x] +++
- [x] ++++

- [x] _This information should also be displayed in the Summary page_. 


**COUNSELLING AND TREATMENT SECTION:** 
13. In the Counselling  section, after the Planned birth place, add the following section:

- [x] Expected delivery method (select one )
- Vaginal delivery
- Assisted vaginal delivery
- Cesarean

**Comment by Naima-Bashir** [comment]
Naima's rough LoE estimations: 

1. Add a section Current Medical Information after Past health conditions. A user should be able to select multiple options. This touches on the `anc_profile.json` , `anc_profile.properties `and `contact summary.ym`l to write the rules. Writing the rules(display) may take quite some effort **(3 days)**.
2. Add a section - Family member health history after the Current Medical Information section. This touches on the `anc_profile.json` , `anc_profile.properties `and `contact summary.ym`l to write the rules. **(2 days)**
3. In the TT vaccine section (profile section), when one selects Under - immunized , add a new field where one can select the type of TT vaccine (drop down). **1/2 day**
6. In the Obstetric History section, when one selects more than 1 in the number of pregnancies (including this pregnancy), add the following fields. **(1/2 day)**
7. In the Obstetric History section, when one selects more than 1 in the number of pregnancies (including this pregnancy), add the following fields (check boxes and radio buttons) **(1 day)**
8. After the Fetal Assessment section, add a section called Special Examination/ Inspection (check boxes and radio buttons) **1/2 day**
9. In the Physical Exam Page, after the pallor present section, add the following fields (should be asked in the 1st and 4th Contacts ) but not mandatory. Requires logic that does not exist in the current code **(2 days)**
10. In the Physical Exams Page, after the Pelvic Exam section, add the field **(1/4 day)**
11. In the Tests Page, there is the Ultrasound Test section, after the number of fetuses; add the following fields. This requires an expansion panel, check boxes and radio buttons. Note, the tests page may slow in terms of performance. **(1 day)**
12. In the Urine Test section, add this field after the Urine dipstick section: Reducing substances test **(1/4 day)**
13. In the Counselling section, after the Planned birth place, add the following section **(1/4 day)**

**Comment by Naima-Bashir** [comment]
Hi @mergygayatri 
For point 2 mentioned here:  **Add a section - Family member health history after the Current Medical Information section. A user should be able to select multiple options** , does this also need to be displayed in the summary section?

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir. Yes, please add. 
In terms of dystocia, we can use "Obstructed labor due to shoulder dystocia". Thank you.

**Comment by Naima-Bashir** [comment]
Hi @mergygayatri   We are progressing well with the Additional fields ticket. There are some questions that require your clarification:

2. Add a section - Family member health history after the Current Medical Information section. A user should be able to select multiple options (check boxes): 

- [x] Hypertension
- [x] Heart disease
- [x] Mental health issues
- [x] Diabetes
- [x] TB
- [x] Blood disorder
- [x] Asthma
- [x] Allergic reactions
- [x] Hepatitis B
- [x] Other - text field for other

_This information should also be displayed in the Summary page.
The choices made here should also reflect on the Counselling and Treatment section. E.g if one selects Diabetes, there should be a logic that is included in the C&T section._

**Could you kindly update the Additional Fields Data Dictionary with the exact wordings of what needs to be displayed in the Counseling and Treatment section. We would like to know how it affects the C&T section in terms of what questions to display when one makes a selection above.** 

Same goes for number **4:** The Woman's Behavior section - after the Caffeine, Tobacco section, add a new filed: History of risky behavior 1 month before pregnancy. A user can select multiple options (checkbox):

**Comment by Naima-Bashir** [comment]
During today's standup with the SID team; we did a walk through of the additional fields that were added. 
The feedback that was received was:

- [x] 1. Remove the following sections when one selects Trimester 1: Amniotic Fluid, Placenta Location  
- [x] 2. Change the title TT Vaccine Type to TT Vaccine Dose. Ensure there is a space between the letter and number e.g TT 1
- [x] 3. In the Obstetric History section, when one selects more than 1 in the number of pregnancies , ensure the added fields are repeated if one selects 2 or more previous pregnancies. E.g repeat the additional fields if one says they had 3 pregnancies
- [x] 4. After the Fetal Assessment section, add a section called Special Examination/ Inspection; remove the mandatory asteriks
- [x] 5. In the Urine Test section, add this field after the Urine dipstick section: Reducing substances test (mandatory): The word none should be Negative
- [x] 6. In the summary page, ensure there are spacing in the check boxes selected e.g medical history
- [x] 7. In the Summary page, the word other (specify) should be removed. This means that if one selects the option other, one must specify what they are taking. Ensure the field other is mandatory if one selects it. 
- [x] 8. @mergygayatri to add the C&T logic for the Special Examination Section if one selects abnormal in any of the special examination tests

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir and @junaidwarsivd,
Please make changes in the dictionary (item number 7) as written below:
1. Special examination: Inspection/ inspekulo --> Pelvic exam
2. Fluxes --> Vaginal bleeding
3. Flour --> Vaginal discharge
4. Porsio --> Cervical portio

Also, I would like to confirm that I have completed [the C&T logic](https://docs.google.com/spreadsheets/d/171Va6UfgqG9nOE4ATo1SGfXg8oE13Ra1/edit?usp=sharing&ouid=104871085518893178803&rtpof=true&sd=true) for Current medical information, Family member health history, History of risky behavior 1 month before pregnancy, and Pelvic exam.

**Comment by Naima-Bashir** [comment]
QA Feedback:

1. Change the following words to (item number 7):
- [x] Special examination: Inspection/ inspekulo --> Pelvic exam
- [x] Fluxes --> Vaginal bleeding
- [x] Flour --> Vaginal discharge
- [x] Porsio --> Cervical portio

- [x] 2. In the Obstetric History section, when one selects more than 1 in the number of pregnancies (including this pregnancy), add the following fields:

Birth attendant: 
- [x] Other- text field for other -- there is no text field for other

- [x] 3. In the Tests Page, there is the Ultrasound Test section, after the number of fetuses; add the following field:
When one selects Trimester 3, show the following fields:
Fetal Presentation
- [x] Other- text field for other -- there is no text field for other

- [x] 4. Translate the words Previous Pregnancies  and Pregnancy 2 and 3 (Profile Page)
- [x] 5. In the number of pregnancies, limit the year of birth and weight (grams) to 4 and 2 digits respectively 
- [x]  6. In the Birth Attendant section, change the word Dokter unum to Dokter spesialis
- [x] 7. In the Pregnancy Complications section, change the word Tidak ada to Tidak ada komplikasi kebidanan
- [x] 8. In the Pregnancy Complications section, Add the word Distosia bahu in the list of options 
- [x] 9. In the TT Vacine Dose; add the word TT ke-1 (Bahasa)
- [x] 10. Translate the title Special Examination Inspection to **Pemeriksaan khusus: Inspeksi/ inspekulo**
- [x] 11. In the word Trimester add the following words to both 1 and 3 : **Hasil USG Trimester I & III**
- [x] 12 In the Trimester I Ultrasound Test, add the following field: **Same with gestational age** with a Yes and No radio button and **Sesuai usia kehamilan** in Bahasa
- [x] 13. In the Janin section (fetus) change the words **Hidup** and **Tidak Hidup** to **Tunggal** and **Ganda**
- [x] 14. Change the word Prentasi janin to **Presentasi** and the radio buttons to say: **Kepala, Bokong, Letak lintag**
- [x] 15. Add the word Plasenta  with Normal and Tidak as it's radio buttons
cc @junaidwarsivd

**Comment by Naima-Bashir** [comment]
QA Feedback 12/09/2023:

Change the following words to (item number 7):
- [x]  Special examination: Inspection/ inspekulo --> Pelvic exam
- [x]  Fluxes --> Vaginal bleeding
- [x]  Flour --> Vaginal discharge
- [x]  Porsio --> Cervical portio

- [x]  2. In the Obstetric History section, when one selects more than 1 in the number of pregnancies (including this pregnancy), add the following fields:
 Birth attendant:
- [x]  Other- text field for other -- there is no text field for other
- [x]  3. In the Tests Page, there is the Ultrasound Test section, after the number of fetuses; add the following field:
When one selects Trimester 3, show the following fields:
- [x] Fetal Presentation
- [x]  Other- text field for other -- there is no text field for other
- [x]  4. Translate the words Previous Pregnancies and Pregnancy 2 and 3 (Profile Page)
- [x]  5. In the number of pregnancies, limit the year of birth and weight (grams) to 4 and 2 digits respectively
- [x]  6. In the Birth Attendant section, change the word Dokter unum to Dokter spesialis
- [x]  7. In the Pregnancy Complications section, change the word Tidak ada to Tidak ada komplikasi kebidanan
- [x]  8. In the Pregnancy Complications section, Add the word Distosia bahu in the list of options
- [x]  9. In the TT Vacine Dose; add the word TT ke-1 (Bahasa)
- [x]  10. Translate the title Special Examination Inspection to Pemeriksaan khusus: Inspeksi/ inspekulo
- [x]  11. In the word Trimester add the following words to both 1 and 3 : Hasil USG Trimester I & III
- [x]  12 In the Trimester I Ultrasound Test, add the following field: Same with gestational age with a Yes and No radio button and Sesuai usia kehamilan in Bahasa
- [x]  13. In the Janin section (fetus) change the words Hidup and Tidak Hidup to Tunggal and Ganda
- [x]  14. Change the word Prentasi janin to Presentasi and the radio buttons to say: Kepala, Bokong, Letak lintag
- [x]  15. Add the word Plasenta with Normal and Tidak as it's radio buttons

**Comment by Naima-Bashir** [comment]
- [x] Translate the words Special examination: Inspection/ inspekulo
- [x] In the USG tests page- add a section:  Jumla with two radio buttons: (Hidup and tidak hidup- )
- [x] In the Jumla Janin section (fetus) change the words Hidup and Tidak Hidup to Tunggal and Ganda
- [x] In the word Trimester add the following words to both 1 and 3 : Hasil USG Trimester I & III
- [x]  12 In the Trimester I Ultrasound Test, add the following field: Same with gestational age with a Yes and No radio button and Sesuai usia kehamilan in Bahasa
- [x] Change the word Prentasi janin to Presentasi
- [x]  Add the word Plasenta with Normal and Tidak as it's radio buttons

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir, please find my QA results as written below:
1. Penolong persalinan (birth attendant): wrong error message. Currently it says ["mohon sebutkan obat-obatan terlarang lain yang digunakan".](https://drive.google.com/file/d/14c9mkmZEKu9CqxiNPS7VKJ-NbKOq-CtI/view?usp=sharing). It should say "Sebutkan penolong persalinan lain-lain".
2. Riwayat perilaku berisiko 1 bulan sebelum hamil (History of risky behavior 1 month before pregnancy): [[the risk flag appears on C&T,](https://drive.google.com/file/d/14tQEcusRcutx62mO--6hG-XC5RPD-Uo4/view?usp=sharing) while[ it should appear below the question](https://drive.google.com/file/d/14WSb7Wr0MEGN1mkWtlc9MyD01OqS-Ktc/view?usp=sharing). ](https://drive.google.com/file/d/14wpPNCiZr8VgGIbqUc3vUG6TIu74-aOS/view?usp=sharing)
3. **_Inspection_**/ inspekulo: It is in English while the app is in Indonesian. It should be Inspeksi/ inspekulo
4. Urethra: It is in English while the app is in Indonesian. It should be uretra.
5. Porsi serviks: This should be porsio, not porsi. "o" is missing.
6. Inspekulo: After clicking one of the option, it cannot be cancelled. There will be a case where the user accidentally clicks on the option. So, we should have a feature where we can cancel the answer. See [video minute 7:35](https://drive.google.com/file/d/15_N6NMwfhwAtczL_QX-qzBdLfSJ3h7QP/view?usp=sharing). In this video, I was trying to click the option that I had selected in order to cancel the answer but it was not working. 
7. USG (ultrasound) trimester 1: GS, CRL, DJJ, should be in numeric only and up to 2 digits.
8. USG (ultrasound) trimester 3: fetal weight field should be up to 4 numeric digits.
9. USG (ultrasound) trimester 3: presentasi: letak **_lintag_**. This should be lintang. "n" is missing.
10. USG (ultrasound) trimester 3: BPD, HC, AC, FL, SPD cairan ketuban, usia kehamilan should be in numeric, and up to 2 digits. 
11. Urine test: Urin dipstik and urin reduksi do not have follow up fields (results). Both of these tests should have follow up fields in order to report the test result.
12. Urine test: urin reduksi tes. This should be urin reduksi, without "tes"
13. Summary page before simpan+selesai: [Hasil usg trimester i. "usg" and "i" should be in capital letters "USG" and "I".](https://drive.google.com/file/d/158hINbsni8ovmKtBdHljKC7wG33R_iM9/view?usp=sharing)

**Comment by Naima-Bashir** [comment]
NAIMA'S COMMENTS ON THE ABOVE: 

- [x] Penolong persalinan (birth attendant): wrong error message. Currently it says ["mohon sebutkan obat-obatan terlarang lain yang digunakan".](https://drive.google.com/file/d/14c9mkmZEKu9CqxiNPS7VKJ-NbKOq-CtI/view?usp=sharing). It should say "Sebutkan penolong persalinan lain-lain".  -- **This can be worked on**
- [ ] Riwayat perilaku berisiko 1 bulan sebelum hamil (History of risky behavior 1 month before pregnancy): [[the risk flag appears on C&T,](https://drive.google.com/file/d/14tQEcusRcutx62mO--6hG-XC5RPD-Uo4/view?usp=sharing) while[ it should appear below the question](https://drive.google.com/file/d/14WSb7Wr0MEGN1mkWtlc9MyD01OqS-Ktc/view?usp=sharing). ](https://drive.google.com/file/d/14wpPNCiZr8VgGIbqUc3vUG6TIu74-aOS/view?usp=sharing) -- **the attention flags for this item was not defined in the original data dictionary shared and was therefore not implemented.** 
- [x] Inspection/ inspekulo: It is in English while the app is in Indonesian. It should be Inspeksi/ inspekulo --**Kindly share a screenshot of this**
- [x] Urethra: It is in English while the app is in Indonesian. It should be uretra. -- **This can be worked on**
- [x] Porsi serviks: This should be porsio, not porsi. "o" is missing.-- **kindly share a screenshot of this**
- [ ] Inspekulo: After clicking one of the option, it cannot be cancelled. There will be a case where the user accidentally clicks on the option. So, we should have a feature where we can cancel the answer. See [video minute 7:35] (https://drive.google.com/file/d/15_N6NMwfhwAtczL_QX-qzBdLfSJ3h7QP/view?usp=sharing). In this video, I was trying to click the option that I had selected in order to cancel the answer but it was not working. -- **Unselecting an option was not defined in the original data dictionary and was therefore not implemented.** 
- [x] USG (ultrasound) trimester 1: GS, CRL, DJJ, should be in numeric only and up to 2 digits. **--this can be worked on**
- [x] USG (ultrasound) trimester 3: fetal weight field should be up to 4 numeric digits. **--this can be worked on**
- [x] USG (ultrasound) trimester 3: presentasi: letak lintag. This should be lintang. "n" is missing. **--this can be worked on**
- [x] USG (ultrasound) trimester 3: BPD, HC, AC, FL, SPD cairan ketuban, usia kehamilan should be in numeric, and up to 2 digits. **--this can be worked on**
- [x] Urine test: Urin dipstik and urin reduksi do not have follow up fields (results). Both of these tests should have follow up fields in order to report the test result. -- **We can discuss this tomorrow during the standup**
- [x] Urine test: urin reduksi tes. This should be urin reduksi, without "tes" **--this can be worked on**
- [ ] Summary page before simpan+selesai: [Hasil usg trimester i. "usg" and "i" should be in capital letters "USG" and "I".](https://drive.google.com/file/d/158hINbsni8ovmKtBdHljKC7wG33R_iM9/view?usp=sharing) **--this can be worked on**

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir, please find the screenshots:
1. [Porsi--> porsio](https://drive.google.com/file/d/1r6-4xsxT86ItDvhPtHD-MCUAdnK_Xia5/view?usp=sharing)
2. [Inspection --> inspeksi ](https://drive.google.com/file/d/1nnP57jUnKnnzsPgkaOfugiZksdF77eOg/view?usp=sharing)

**Comment by mergygayatri** [comment]
Berat lahir (birth weight): wrong format and wrong constraint. This field should be in numeric format, and up to 4 digits. [Currently it only allows up to 2 digits.](https://drive.google.com/file/d/14JFH0C6KDZi0Cp3VVSr_R6y9SfQ3SiKV/view?usp=sharing)

**Comment by Naima-Bashir** [comment]
QA Feedback:

- [x] Penolong persalinan (birth attendant): wrong error message. Currently it says ["mohon sebutkan obat-obatan terlarang lain yang digunakan".](https://drive.google.com/file/d/14c9mkmZEKu9CqxiNPS7VKJ-NbKOq-CtI/view?usp=sharing). It should say "Sebutkan penolong persalinan lain-lain". -- **PASSED QA**
- [x]  Riwayat perilaku berisiko 1 bulan sebelum hamil (History of risky behavior 1 month before pregnancy): [[the risk flag appears on C&T,](https://drive.google.com/file/d/14tQEcusRcutx62mO--6hG-XC5RPD-Uo4/view?usp=sharing) while[ it should appear below the question](https://drive.google.com/file/d/14WSb7Wr0MEGN1mkWtlc9MyD01OqS-Ktc/view?usp=sharing). ](https://drive.google.com/file/d/14wpPNCiZr8VgGIbqUc3vUG6TIu74-aOS/view?usp=sharing) -- the attention flags for this item was not defined in the original data dictionary shared-- _IN PROGRESS_
- [x]  Inspection/ inspekulo: It is in English while the app is in Indonesian. It should be Inspeksi/ inspekulo  -- **PASSED QA**
- [x]  Urethra: It is in English while the app is in Indonesian. It should be uretra. --  -- **PASSED QA**
- [x]  Porsi serviks: This should be porsio, not porsi. "o" is missing.--  -- **PASSED QA**
- [x]  Inspekulo: After clicking one of the option, it cannot be cancelled. There will be a case where the user accidentally clicks on the option. So, we should have a feature where we can cancel the answer. See [video minute 7:35] (https://drive.google.com/file/d/15_N6NMwfhwAtczL_QX-qzBdLfSJ3h7QP/view?usp=sharing). In this video, I was trying to click the option that I had selected in order to cancel the answer but it was not working. -- _has not been implemented as it's out of scope._
- [x]  USG (ultrasound) trimester 1: GS, CRL, DJJ, should be in numeric only and up to 2 digits. --this can be worked on
- [x]  USG (ultrasound) trimester 3: fetal weight field should be up to 4 numeric digits. --**FAILED QA**
- [x]  USG (ultrasound) trimester 3: presentasi: letak lintag. This should be lintang. "n" is missing. --this can be worked on
- [x]  USG (ultrasound) trimester 3: BPD, HC, AC, FL, SPD cairan ketuban, usia kehamilan should be in numeric, and up to 2 digits. **FAILED QA**
- [x]  Urine test: Urin dipstik and urin reduksi do not have follow up fields (results). Both of these tests should have follow up fields in order to report the test result. -- We can discuss this tomorrow during the standup - **IN PROGRESS**
- [x]  Urine test: urin reduksi tes. This should be urin reduksi, without "tes" **PASSED QA**
- [x]  Summary page before simpan+selesai: [Hasil usg trimester i. "usg" and "i" should be in capital letters "USG" and "I".](https://drive.google.com/file/d/158hINbsni8ovmKtBdHljKC7wG33R_iM9/view?usp=sharing) ----**FAILED QA**

**Comment by Naima-Bashir** [comment]
- [x] 1. Fetal weight field should be up to 4 digits.
- [x] 2. Ultasound Test Should have follow up fields that pop up when one selects either Trimester 1 or 3. See point 10 in [this](https://github.com/opensrp/opensrp-client-anc/issues/969#issuecomment-1687990031) list
- [x] 3. In the summary page, the word Uretha is still in English (should be uretra)
- [x] In the summary page, the word USG I is still in small letters
- [x] 4. Riwayat perilaku berisiko 1 bulan sebelum hamil (History of risky behavior 1 month before pregnancy):the risk flag appears on C&T- IN PROGRESS
- [x] 5. Urine test: Urin dipstik and urin reduksi do not have follow up fields (results). Both of these tests should have follow up fields in order to report the test result.
cc @hilpitome
