### ISSUE TITLE
[Ona Support Request]: Performance Optimization for ANC Module Zambia

### ISSUE THREAD

**Issue by MwambaK** [OpenSRP/opensrp-client-anc#990]
### Affected App or Server Version

namai zm v10029

### What kind of support do you need?

The ANC reference application is experiencing performance issues, particularly on 2GB and 3GB RAM devices, with noticeable slowness reported during interactions with the profile, obstetric history, and tests containers.

### What is the acceptance criteria for your support request?

The application should demonstrate improved performance on 2GB and 3GB tablets, with faster response times during interactions with the profile, obstetric history, and tests containers.

### Relevant Information

- The profile container is slow, particularly when selecting LMP due to background calculations.

- The obstetric history page is slow when loading pregnancies, as a large number of calculations and relevance rules have been added.

- Tests container performance is affected, even after implementing individual relevance forms for each sub-form.

- Diagnostic tests and imaging container, especially Blood Glucose test, TB test, Blood Group, HIV test, and Partner Syphilis, exhibit slow performance.

- Some test forms have improved, but completing certain forms may impact subsequent test forms, leading to increased slowness.

- Radio buttons require multiple taps for selection initially, and subsequent selections, such as changing from "Done today" to "Ordered," introduce lag.

**Comment by Naima-Bashir** [comment]
In regards to the Slow Test Page we did some investigations and we have come up with two possible solutions to improve the performance.  

**SOLUTION 1:**

1. Improve the performance by separating the relevance logic for each subform. Below, you will find detailed instructions on how to implement the separation of the relevance and calculations to a single file for the sub forms:
2. Pick a test you would like to move e.g if it is a TB screening test
3. Create a new rule/file inside the 'opensrp_[repo]/opensrp-anc/src/main/assets/rule' folder for the test. In this case, name it 'tb_screening_relevance_rules.yml.' (please be keen with the file extension, otherwise the rule will not be recognized).
4. Go to the 'tests_relevance_rule.yml' file and select all the relevance rules related to 'tb_screening.'
5. Copy these rules to the 'tb_screening_relevance_rules.yml' file. Note that each rule starts with three dashes (---) and most likely ends with the line '- "isRelevant = true".'
6. Go to the 'tests_tb_screening_sub_form.json' file and replace all occurrences of 'tests_calculation_rules.yml' with 'tb_screening_calculation_rules.yml.'
7. Install the app, fill out a new contact, and navigate to the tests container. Click on 'TB screening tests' and confirm that the form behaves as before.
8. The same set of instructions will be applicable to calculations. To continue with the TB screening example:
9. Create a new rule or file in the opensrp_[repo]/opensrp-anc/src/main/assets/rule folder. In this case it will be tb_screening_calculation_rules.yml
10. Go to tests_calcalculation_rules.yml and copy all the rules that relate to the tb subform and paste them to the new tb_screening_calculation_rules.yml file.
11. Go to the tests_tb_screening_sub_form.json file and replace all occurrences  of tests_calcalculation_rules.yml with tb_screening_calculation_rules.yml
12. Install the app, fill out a new contact. Once you are at the tests container, click on tb screening tests and confirm that the form still behaves as before.
13. Instead of launching the tests as a subform we can launch the forms from a single activity. This involves creating a new Activity. The purpose of this is to remove the relationship between the forms and subforms and launch the subforms independently.

**SOLUTION 2:** 

1. Launching the forms from a single activity instead of launching the tests as a subform. This involves creating a new Activity. The purpose of this is to remove the relationship between the forms and subforms and launch the subforms independently.
2. Files or sections to touch on the code:
3. Create an activity similar to MainContact Activity to launch the tests this time. It should be invoked in the MainContact Activity.
4. Modify the code that launches the Tests form in MainContact activity to launch a new Activity. This can be called TestsAcitvity for example. It will list down all the tests and the specific forms
5. List the tests in the new activity as they appear on the existing architecture
6. Launch the test forms as they appear in the current activity.
7. Remove the current ANC test as an XML view instead of  a JSON form
8. Launch the new JSON ANC test forms similar to the way we launch each subform in the new activity.ie launch JSONFORMACTIVITY in that activity. You can use the logic that launches QuickCheck


NOTE: The reason for solution 2 is to omit ANC Tests JsonFormActivity which is resource-intensive.

Kindly implement these changes and please let us know if they work as expected. We are here to provide support and look forward to hearing from you.

**Comment by Naima-Bashir** [comment]
From the Bluecode team: _Yes we had managed to update the native form version to the version you had suggested in your previous email, though the first solution had been implemented prior to the ticket being opened and was in our production build at the time- SOLUTION 1_

**Comment by Naima-Bashir** [comment]
This has been resolved and confirmed by the client
