### ISSUE TITLE
[Ona Support Request]: ANC visit for postterm client unable to be finalized and submitted 

### ISSUE THREAD

**Issue by edwardsutanto** [OpenSRP/opensrp-client-anc#992]
### Affected App or Server Version

Latest APK

### What kind of support do you need?

For postterm client (40 weeks 3 days), we are unable to finalize and submit the ANC visit. Instead, the start ANC visit button still showed that ANC visit is currently ongoing. If we clicked the ANC visit button (as shown in the video below), it instead asked to register birth/delivery of the pregnancy. 
 
Due to privacy issue, credentials and specific client ID where we encountered the issue have been shared to ONA team personally.

### What is the acceptance criteria for your support request?

ANC visit for postterm client should be able to be finalized and submitted

### Relevant Information

https://drive.google.com/file/d/1yWv1tMhK26atmQ8EO0zEOeHpjp0zQy6I/view?usp=drive_link

**Comment by Naima-Bashir** [comment]
From the investigations done today, it appears that the issue stems from the Contact Summary Page (screenshot below). The page should show the upcoming contacts and the specific contact , instead it shows characters and numbers. After the user goes back to the list page, it still shows contact 2 instead of going to contact 3.  
![1000000067](https://github.com/opensrp/opensrp-client-anc/assets/61143692/15c593a7-956c-49a6-937a-4db954245b4b)

**Comment by Naima-Bashir** [comment]
CORRECT IMPLEMENTATION: At GA 41 weeks, the contact button on the main register page changes to a blue Due Delivery button. When you click on this button, the below widget pops up:
The bug here is that the pop up does not show.
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/1550cbd5-91bb-4314-8d52-4ecd43978fde)

- [ ]  Display gest_age from the woman's record.
- [ ]  Display woman's edd. Calculate and display how many days ago it was.
- [ ]  Replace Charity with woman's first_name.
- [ ]  The Record birth button opens the ANC Close form (https://github.com/opensrp/opensrp-client-anc/issues/3)
- [ ]  The Cancel button (or tapping device back button or tapping anywhere outside the widget) closes the widget.
cc @hilpitome

**Comment by hilpitome** [comment]
The reason why the `%1d` in the text Contact `%1$d` is not replaced with the contact number in contact summary page is because the patient no longer has future visits. 
This particular patient has issues. The Gestational Age showing in the popup and the one on the list view are different.

![Screenshot from 2024-01-23 16-23-42](https://github.com/opensrp/opensrp-client-anc/assets/12864384/8fd213fa-c3a4-44a8-9bfd-de5aaeac9081)

![Screenshot from 2024-01-23 16-23-30](https://github.com/opensrp/opensrp-client-anc/assets/12864384/62a4d841-7177-40b5-b644-58afa7b34c18)

**Comment by Naima-Bashir** [comment]
The finalize contact bug has appeared again on another patient who was also 40 weeks pregnant. Video can be found here: [https://drive.google.com/file/d/1U8tGJP2DM8qgJpb2ASoER5VHXfTTYUg6/view](url)
