### ISSUE TITLE
[Ona Support Request]: Manual Encounter feature

### ISSUE THREAD

**Issue by AngelaKabari** [OpenSRP/opensrp-client-anc#997]
### Affected App or Server Version

Branch for this issue: https://github.com/dodosi/opensrp_rw/tree/encounter_date_issue_fix.

### What kind of support do you need?

Implementation of the manual encounter feature. This is a new feature, specifically requested by healthcare providers, which empowers users to manually designate the date of contact visits with patients. It enables retrospective recording of encounters with pregnant women within a 30-day timeframe, ensuring flexibility and data accuracy even when immediate entry isn't feasible.

### What is the acceptance criteria for your support request?

- [ ] Allow for the retrospective entry of encounters - ANC encounters from the past can be accurately documented in the system at a later date, preserving the original encounter date.
Ensure that the manually entered encounter correctly updates the following parameters:
- [ ] Estimated Date of Delivery (EDD)
- [ ] Gestational Age (GA)
- [ ] Ultrasound Calculations
- [ ] Next Contact Visit Date

### Relevant Information

The tasks involved in implementing this feature are:
- Create a date field to store manual encounter date on any JSON Form.
- Add the above date to global variables. This can be done at code level(ContactJsonFormActivity, PreviousContactDetailsActivity, ProfileActivity, ProfileContactsFragment,ANCRulesHelper, ContactInterractor, ProfilePresenter, PatientRepository) and fix any bugs you might encounter.
- Update calculation rules (Ultrasound GA, EDD and LMP GA and EDD) based on that date above.
- Add it to profile overview files to display it on the app as the Visit Date.
- Test if the updated GA and EDD dates work correctly.

Further detailed information is available in this [Manual Encounter Feature specification](https://docs.google.com/document/d/1nugzcUfpLT2uG2iky_CqrVPbYXELBpSAG1kCvKyv7Rk/edit?usp=sharing)

**Comment by Naima-Bashir** [comment]
QA and Engineering checklist:

- [x] Ensure that the application has a date picker in the Quick Check Form. The date picker needs to be in the Quick Check as the calculations for Ultrasound, GA and EDD are in the Profile Container. One therefore needs to select the manual encounter date so that the calculations are correct.
- [x] Ensure that the date picker has a cap of 30 days. This allows the user 30 days to backdate the contact visit but not more than 30 days. 
- [x] Ensure that the calculations in the Gestational Age using LMP are correctly calculated. Use this link to aid in verification: https://www.uptodate.com/contents/calculator-estimated-date-of-delivery-edd-patient-education
- [x] Ensure that the calculations in the Ultrasound are correct. 
- [x] Ensure that the Gestational Age using Ultrasound calculations are correct. Use this link to aid in verification: https://flo.health/tools/due-date-by-ultrasound
- [x] Ensure that the EDD using LMP is correct 
- [x] Ensure that the EDD using ultrasound is correct. 
- [ ] Once complete, ensure that the Upcoming contact dates are calculated correctly in the summary form.

**Comment by Naima-Bashir** [comment]
**QA CHECKLIST**

- [x]  Ensure that the application has a date picker in the Quick Check Form. The date picker needs to be in the Quick Check as the calculations for Ultrasound, GA and EDD are in the Profile Container. One therefore needs to select the manual encounter date so that the calculations are correct.
- [x]  Ensure that the date picker has a cap of 30 days. This allows the user 30 days to backdate the contact visit but not more than 30 days.
- [x]  Ensure that the calculations in the Gestational Age using LMP are correctly calculated. Use this link to aid in verification: https://www.uptodate.com/contents/calculator-estimated-date-of-delivery-edd-patient-education
- [x]  Ensure that the calculations in the Ultrasound are correct.
- [x]  Ensure that the Gestational Age using Ultrasound calculations are correct. Use this link to aid in verification: https://flo.health/tools/due-date-by-ultrasound
- [x]  Ensure that the EDD using LMP is correct
- [x]  Ensure that the EDD using ultrasound is correct.
- [x] Ensure that GA from SFH or palpitation is calculated correctly. Use this link for verification: [https://perinatology.com/calculators/Estimation%20of%20Fetal%20Weight%20and%20Age.htm]
- [x] Ensure that EDD using SFH or abdominal palpitation is calculated correctly
- [x]  Once complete, ensure that the Upcoming contact dates are calculated correctly in the summary form.

**Comment by Naima-Bashir** [comment]
Hi @hilpitome  Please find the second round of QA below:

- [x] Verify that the application has a date picker in the Quick Check Form **- PASSED QA**
- [x] Verify that the date picker has a cap of 30 days. This allows the user 30 days to backdate the contact visit but not more than 30 days - **PASSED QA**
- [x] Verify that the calculations in the Gestational Age using LMP are correctly calculated. I used this link to aid in verification - **PASSED QA**
- [x] Verify that the calculations in the Ultrasound are correct - **PASSED QA**
- [x] Verify that the Gestational Age using Ultrasound calculations are correct. I used this link to aid in verification - **PASSED QA**
- [x] Verify that the EDD using LMP is correct- **PASSED QA**
- [x] Verify that the EDD using ultrasound is correct - **PASSED QA**
- [ ] Verify that the GA on the profile summary and the GA shown on the contact summary as similar- **FAILED QA**
- [x] Verify that the upcoming contact dates are calculated correctly in the summary form - **PASSED QA**

I'll do a third round of QA and share feedback.

**Comment by Naima-Bashir** [comment]
FINAL QA: 
- [x] Verify that the application has a date picker in the Quick Check Form - PASSED QA
- [x]  Verify that the date picker has a cap of 30 days. This allows the user 30 days to backdate the contact visit but not more than 30 days - PASSED QA
- [x] Verify that the calculations in the Gestational Age using LMP are correctly calculated. I used this link to aid in verification - PASSED QA
- [x] Verify that the calculations in the Ultrasound are correct - PASSED QA
- [x] Verify that the Gestational Age using Ultrasound calculations are correct. I used this link to aid in verification - PASSED QA
- [x] Verify that the EDD using LMP is correct- PASSED QA
- [x] Verify that the EDD using ultrasound is correct - PASSED QA
- [x] Verify that the GA on the profile summary and the GA shown on the contact summary as similar- FAILED QA
- [x] Verify that the upcoming contact dates are calculated correctly in the summary form - PASSED QA
- [x] Verify EDD using SFH or abdominal palpitation - PASSED QA 
- [x] Verify that the GA on the profile summary and the GA shown on the contact summary as similar- PASSED QA
- [x] Verify that the upcoming contact dates are calculated correctly in the summary form - PASSED QA
